---
# Role for Backstage to read Tekton resources in dotnet-demo namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backstage-tekton-reader
  namespace: dotnet-demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: dotnet-demo
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - pipelines
      - pipelineruns
      - tasks
      - taskruns
      - conditions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - events
    verbs:
      - get
      - list
      - watch
---
# RoleBinding to grant Backstage service account access
# Note: Backstage pods use the default service account in developer-hub namespace
# The service account name is typically: developer-hub-<instance-name>
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backstage-tekton-reader-binding
  namespace: dotnet-demo
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app: dotnet-demo
subjects:
  # Backstage service account - RHDH typically uses 'developer-hub' or 'developer-hub-<instance-name>'
  # If using default service account, it will be automatically mounted
  - kind: ServiceAccount
    name: developer-hub
    namespace: developer-hub
  # Also grant access to default service account (if Backstage uses it)
  - kind: ServiceAccount
    name: default
    namespace: developer-hub
roleRef:
  kind: Role
  name: backstage-tekton-reader
  apiGroup: rbac.authorization.k8s.io

