apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dotnet-demo
  namespace: default
  description: .NET Demo Application - Sample application demonstrating CI/CD pipeline with Nexus artifact publishing
  annotations:
    # GitLab Integration (standard format)
    gitlab.com/project-slug: maximilianoPizarro/connectivity-link
    # Backstage Standard Annotations
    backstage.io/view-url: http://nexus-nexus2.apps.cluster-gpzvq.gpzvq.sandbox670.opentlc.com/#browse/browse:releases:com/example/dotnet-demo
    backstage.io/source-location: url:https://gitlab.com/maximilianoPizarro/connectivity-link/-/tree/main/dotnet-demo
    backstage.io/techdocs-ref: dir:.
    # Kubernetes Integration
    backstage.io/kubernetes-namespace: workshop-pipelines
    backstage.io/kubernetes-id: dotnet-demo
    backstage.io/kubernetes-label-selector: 'app=dotnet-demo'
    # Tekton Pipeline Integration (Janus IDP format)
    janus-idp.io/tekton: dotnet-demo-pipeline
    # ArgoCD Integration (using backstage.io prefix)
    backstage.io/argocd-app-name: dotnet-demo
    backstage.io/argocd-app-namespace: openshift-gitops
    backstage.io/argocd-app-url: https://openshift-gitops-server-openshift-gitops.apps.cluster-gpzvq.gpzvq.sandbox670.opentlc.com/applications/dotnet-demo
  links:
    - url: http://nexus-nexus2.apps.cluster-gpzvq.gpzvq.sandbox670.opentlc.com
      title: Nexus Repository
      icon: storage
    - url: http://nexus-nexus2.apps.cluster-gpzvq.gpzvq.sandbox670.opentlc.com/#browse/browse:releases:com/example/dotnet-demo
      title: View Artifacts in Nexus
      icon: package
    - url: https://gitlab.com/maximilianoPizarro/connectivity-link/-/tree/main/dotnet-demo
      title: Source Code
      icon: code
    - url: https://tekton-dashboard.apps.cluster-gpzvq.gpzvq.sandbox670.opentlc.com/#/namespaces/workshop-pipelines/pipelines/dotnet-demo-pipeline
      title: View Pipeline
      icon: build
    - url: https://tekton-dashboard.apps.cluster-gpzvq.gpzvq.sandbox670.opentlc.com/#/namespaces/workshop-pipelines/pipelineruns
      title: Pipeline Runs
      icon: history
  tags:
    - dotnet
    - csharp
    - nexus
    - cicd
    - demo
    - artifact-repository
    - tekton
spec:
  type: service
  lifecycle: production
  owner: application-team
  system: cicd-platform
  dependsOn:
    - component:default/workshop-pipelines

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: dotnet-demo-api
  description: .NET Demo API endpoints
spec:
  type: rest
  lifecycle: production
  owner: application-team
  definition: |
    openapi: "3.0.0"
    info:
      title: .NET Demo API
      version: "1.0.0"
    paths:
      /api/health:
        get:
          summary: Health check endpoint
      /api/version:
        get:
          summary: Get application version

