apiVersion: v1
kind: Secret
metadata:
  name: nexus-credentials
  labels:
    app: dotnet-demo
  annotations:
    argocd.argoproj.io/sync-wave: "4"    
type: Opaque
stringData:
  username: admin
  password: admin123  # Update with your actual Nexus admin password
  # Note: For production, use Kustomize secretGenerator with environment variables
  # or Sealed Secrets / External Secrets Operator

