apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  labels:
    app.kubernetes.io/version: "0.9"
  annotations:
    tekton.dev/pipelines.minVersion: "0.38.0"
    tekton.dev/categories: Git
    tekton.dev/tags: git
    tekton.dev/displayName: "git clone"
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
    tekton.dev/deprecated: "true"
spec:
  description: >-
    These Tasks are Git tasks to work with repositories used by other tasks
    in your Pipeline.

    The git-clone Task will clone a repo from the provided url into the
    output Workspace. By default the repo will be cloned into the root of
    your Workspace. You can clone into a subdirectory by setting this Task's
    subdirectory param. This Task also supports sparse checkouts. To perform
    a sparse checkout, pass a list of comma separated directory patterns to
    this Task's sparseCheckoutDirectories param.
  workspaces:
    - name: output
      description: The git repo will be cloned onto the volume backing this Workspace.
    - name: ssh-directory
      optional: true
      description: |
        A .ssh directory with private key, known_hosts, config, etc. Copied to
        the user's home before git commands are executed. Used to authenticate
        with the git remote when performing the clone. Binding a Secret to this
        Workspace is strongly recommended over other volume types.
    - name: basic-auth
      optional: true
      description: |
        A Workspace containing a .gitconfig and .git-credentials file. These
        will be copied to the user's home before any git commands are run. Any
        other files in this Workspace are ignored. It is strongly recommended
        to use ssh-directory over basic-auth whenever possible and to bind a
        Secret to this Workspace over other volume types.
    - name: ssl-ca-directory
      optional: true
      description: |
        A workspace containing CA certificates, this will be used by Git to
        verify the peer with when fetching or pushing over HTTPS.
  params:
    - name: url
      description: Repository URL to clone from.
      type: string
    - name: revision
      description: Revision to checkout. (branch, tag, sha, ref, etc...)
      type: string
      default: ""
    - name: refspec
      description: Refspec to fetch before checking out revision.
      default: ""
    - name: submodules
      description: Initialize and fetch git submodules.
      type: string
      default: "true"
    - name: depth
      description: Perform a shallow clone, fetching only the most recent N commits.
      type: string
      default: "1"
    - name: sslVerify
      description: Set the `http.sslVerify` global git config. Setting this to `false` is not advised unless you are sure that you trust your git remote.
      type: string
      default: "true"
    - name: crtFileName
      description: file name of mounted crt using ssl-ca-directory workspace. default value is ca-bundle.crt.
      type: string
      default: "ca-bundle.crt"
    - name: subdirectory
      description: Subdirectory inside the `output` Workspace to clone the repo into.
      type: string
      default: ""
    - name: sparseCheckoutDirectories
      description: Define the directory patterns to match or exclude when performing a sparse checkout.
      type: string
      default: ""
    - name: deleteExisting
      description: Clean out the contents of the destination directory if it already exists before cloning.
      type: string
      default: "true"
    - name: httpProxy
      description: HTTP proxy server for non-SSL requests.
      type: string
      default: ""
    - name: httpsProxy
      description: HTTPS proxy server for SSL requests.
      type: string
      default: ""
    - name: noProxy
      description: Opt out of proxying HTTP/HTTPS requests.
      type: string
      default: ""
    - name: verbose
      description: Log the commands that are executed during `git-clone`'s operation.
      type: string
      default: "true"
    - name: gitInitImage
      description: The image providing the git-init binary that this Task runs.
      type: string
      default: "ghcr.io/tektoncd/github.com/tektoncd/pipeline/cmd/git-init:v0.40.2"
    - name: userHome
      description: |
        Absolute path to the user's home directory.
      type: string
      default: "/home/git"
  results:
    - name: commit
      description: The precise commit SHA that was fetched by this Task.
    - name: url
      description: The precise URL that was fetched by this Task.
    - name: committer-date
      description: The epoch timestamp of the commit that was fetched by this Task.
  steps:
    - name: clone
      image: "$(params.gitInitImage)"
      env:
      - name: HOME
        value: "$(params.userHome)"
      - name: PARAM_URL
        value: $(params.url)
      - name: PARAM_REVISION
        value: $(params.revision)
      - name: PARAM_REFSPEC
        value: $(params.refspec)
      - name: PARAM_SUBMODULES
        value: $(params.submodules)
      - name: PARAM_DEPTH
        value: $(params.depth)
      - name: PARAM_SSL_VERIFY
        value: $(params.sslVerify)
      - name: PARAM_CRT_FILENAME
        value: $(params.crtFileName)
      - name: PARAM_SUBDIRECTORY
        value: $(params.subdirectory)
      - name: PARAM_DELETE_EXISTING
        value: $(params.deleteExisting)
      - name: PARAM_HTTP_PROXY
        value: $(params.httpProxy)
      - name: PARAM_HTTPS_PROXY
        value: $(params.httpsProxy)
      - name: PARAM_NO_PROXY
        value: $(params.noProxy)
      - name: PARAM_VERBOSE
        value: $(params.verbose)
      - name: PARAM_SPARSE_CHECKOUT_DIRECTORIES
        value: $(params.sparseCheckoutDirectories)
      - name: PARAM_USER_HOME
        value: $(params.userHome)
      - name: WORKSPACE_OUTPUT_PATH
        value: $(workspaces.output.path)
      - name: WORKSPACE_SSH_DIRECTORY_BOUND
        value: $(workspaces.ssh-directory.bound)
      - name: WORKSPACE_SSH_DIRECTORY_PATH
        value: $(workspaces.ssh-directory.path)
      - name: WORKSPACE_BASIC_AUTH_DIRECTORY_BOUND
        value: $(workspaces.basic-auth.bound)
      - name: WORKSPACE_BASIC_AUTH_DIRECTORY_PATH
        value: $(workspaces.basic-auth.path)
      - name: WORKSPACE_SSL_CA_DIRECTORY_BOUND
        value: $(workspaces.ssl-ca-directory.bound)
      - name: WORKSPACE_SSL_CA_DIRECTORY_PATH
        value: $(workspaces.ssl-ca-directory.path)
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      script: |
        #!/usr/bin/env sh
        set -eu

        if [ "${PARAM_VERBOSE}" = "true" ] ; then
          set -x
        fi

        if [ "${WORKSPACE_BASIC_AUTH_DIRECTORY_BOUND}" = "true" ] ; then
          cp "${WORKSPACE_BASIC_AUTH_DIRECTORY_PATH}/.git-credentials" "${PARAM_USER_HOME}/.git-credentials"
          cp "${WORKSPACE_BASIC_AUTH_DIRECTORY_PATH}/.gitconfig" "${PARAM_USER_HOME}/.gitconfig"
          chmod 400 "${PARAM_USER_HOME}/.git-credentials"
          chmod 400 "${PARAM_USER_HOME}/.gitconfig"
        fi

        if [ "${WORKSPACE_SSH_DIRECTORY_BOUND}" = "true" ] ; then
          cp -R "${WORKSPACE_SSH_DIRECTORY_PATH}" "${PARAM_USER_HOME}"/.ssh
          chmod 700 "${PARAM_USER_HOME}"/.ssh
          chmod -R 400 "${PARAM_USER_HOME}"/.ssh/*
        fi

        if [ "${WORKSPACE_SSL_CA_DIRECTORY_BOUND}" = "true" ] ; then
           export GIT_SSL_CAPATH="${WORKSPACE_SSL_CA_DIRECTORY_PATH}"
           if [ "${PARAM_CRT_FILENAME}" != "" ] ; then
              export GIT_SSL_CAINFO="${WORKSPACE_SSL_CA_DIRECTORY_PATH}/${PARAM_CRT_FILENAME}"
           fi
        fi
        CHECKOUT_DIR="${WORKSPACE_OUTPUT_PATH}/${PARAM_SUBDIRECTORY}"

        cleandir() {
          # Delete any existing contents of the repo directory if it exists.
          #
          # We don't just "rm -rf ${CHECKOUT_DIR}" because ${CHECKOUT_DIR} might be "/"
          # or the root of a mounted volume.
          if [ -d "${CHECKOUT_DIR}" ] ; then
            # Delete non-hidden files and directories
            rm -rf "${CHECKOUT_DIR:?}"/*
            # Delete files and directories starting with . but excluding ..
            rm -rf "${CHECKOUT_DIR}"/.[!.]*
            # Delete files and directories starting with .. plus any other character
            rm -rf "${CHECKOUT_DIR}"/..?*
          fi
        }

        if [ "${PARAM_DELETE_EXISTING}" = "true" ] ; then
          cleandir || true
        fi

        test -z "${PARAM_HTTP_PROXY}" || export HTTP_PROXY="${PARAM_HTTP_PROXY}"
        test -z "${PARAM_HTTPS_PROXY}" || export HTTPS_PROXY="${PARAM_HTTPS_PROXY}"
        test -z "${PARAM_NO_PROXY}" || export NO_PROXY="${PARAM_NO_PROXY}"

        git config --global --add safe.directory "${WORKSPACE_OUTPUT_PATH}"
        /ko-app/git-init \
          -url="${PARAM_URL}" \
          -revision="${PARAM_REVISION}" \
          -refspec="${PARAM_REFSPEC}" \
          -path="${CHECKOUT_DIR}" \
          -sslVerify="${PARAM_SSL_VERIFY}" \
          -submodules="${PARAM_SUBMODULES}" \
          -depth="${PARAM_DEPTH}" \
          -sparseCheckoutDirectories="${PARAM_SPARSE_CHECKOUT_DIRECTORIES}"
        cd "${CHECKOUT_DIR}"
        RESULT_SHA="$(git rev-parse HEAD)"
        EXIT_CODE="$?"
        if [ "${EXIT_CODE}" != 0 ] ; then
          exit "${EXIT_CODE}"
        fi
        RESULT_COMMITTER_DATE="$(git log -1 --pretty=%ct)"
        printf "%s" "${RESULT_COMMITTER_DATE}" > "$(results.committer-date.path)"
        printf "%s" "${RESULT_SHA}" > "$(results.commit.path)"
        printf "%s" "${PARAM_URL}" > "$(results.url.path)"

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: s2i-dotnet
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: dotnet-demo
spec:
  params:
    - name: VERSION
      description: .NET version to use
      type: string
      default: "8.0"
    - name: OUTPUT_IMAGE
      description: The image reference where the built image will be written
      type: string
  workspaces:
    - name: source
      description: Source code workspace
  steps:
    - name: build-and-push
      image: registry.redhat.io/dotnet/dotnet-80-rhel8:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        # Build the .NET application
        dotnet build --configuration Release
        # Publish the application
        dotnet publish --configuration Release --output ./publish
        # Use buildah to build and push the container image
        # Note: This step assumes buildah is available in the image or we use a different approach
        # For now, we'll just build the app - image building can be done in a separate step if needed
        echo "Application built successfully in ./publish directory"
      volumeMounts:
        - name: source
          mountPath: $(workspaces.source.path)

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: dotnet-build-nuget
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: dotnet-demo
spec:
  params:
    - name: PROJECT_PATH
      description: Path to .NET project directory
      default: "."
    - name: VERSION
      description: Package version
      default: "1.0.0"
  workspaces:
    - name: source
      description: Source code workspace
    - name: cache
      description: NuGet cache workspace
  steps:
    - name: restore
      image: mcr.microsoft.com/dotnet/sdk:8.0
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        cd $(params.PROJECT_PATH)
        dotnet restore
      # Mount cache workspace for NuGet packages
      # Workspaces are automatically available as volumes with name matching workspace name
      volumeMounts:
        - name: cache
          mountPath: /root/.nuget
          subPath: nuget

    - name: build
      image: mcr.microsoft.com/dotnet/sdk:8.0
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        cd $(params.PROJECT_PATH)
        dotnet build --configuration Release

    - name: pack
      image: mcr.microsoft.com/dotnet/sdk:8.0
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        cd $(params.PROJECT_PATH)
        dotnet pack --configuration Release --no-build -p:Version=$(params.VERSION) -p:PackageVersion=$(params.VERSION) -o bin/Release
      # Mount cache workspace for NuGet packages
      volumeMounts:
        - name: cache
          mountPath: /root/.nuget
          subPath: nuget

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: nexus-upload
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: dotnet-demo
spec:
  params:
    - name: NEXUS_URL
      description: Nexus repository URL
    - name: NEXUS_REPOSITORY
      description: Nexus repository name
      default: "releases"
    - name: NEXUS_USERNAME
      description: Nexus username
    # NEXUS_PASSWORD is provided via environment variable from secret
    # No need to pass as parameter for security
    - name: GROUP_ID
      description: Maven group ID
    - name: ARTIFACT_ID
      description: Artifact ID
    - name: VERSION
      description: Artifact version
    - name: PACKAGING
      description: Package type (nupkg, jar, etc.)
      default: "nupkg"
    - name: FILE_PATH
      description: Path to artifact file(s) to upload
  workspaces:
    - name: source
      description: Source workspace containing artifacts
  steps:
    - name: upload-to-nexus
      image: curlimages/curl:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        
        NEXUS_URL=$(params.NEXUS_URL)
        REPO=$(params.NEXUS_REPOSITORY)
        USERNAME=$(params.NEXUS_USERNAME)
        PASSWORD="${NEXUS_PASSWORD}"
        GROUP_ID=$(params.GROUP_ID)
        ARTIFACT_ID=$(params.ARTIFACT_ID)
        VERSION=$(params.VERSION)
        PACKAGING=$(params.PACKAGING)
        
        # Find the artifact file
        ARTIFACT_FILE=$(find $(params.FILE_PATH) -type f -name "*.${PACKAGING}" | head -n 1)
        
        if [ -z "$ARTIFACT_FILE" ]; then
          echo "Error: No artifact file found matching $(params.FILE_PATH)"
          exit 1
        fi
        
        echo "Uploading artifact: $ARTIFACT_FILE"
        echo "To Nexus: $NEXUS_URL/repository/$REPO/"
        
        # Upload to Nexus using REST API
        # For Nexus 2.x, use the service/rest endpoint
        # For Nexus 3.x, use the service/rest/v1/components endpoint
        
        # Try Nexus 3.x format first
        RESPONSE=$(curl -s -w "\n%{http_code}" \
          -u "$USERNAME:$PASSWORD" \
          -X POST \
          -H "Content-Type: multipart/form-data" \
          -F "maven2.groupId=$GROUP_ID" \
          -F "maven2.artifactId=$ARTIFACT_ID" \
          -F "maven2.version=$VERSION" \
          -F "maven2.packaging=$PACKAGING" \
          -F "maven2.asset1=@$ARTIFACT_FILE" \
          -F "maven2.asset1.extension=$PACKAGING" \
          "$NEXUS_URL/service/rest/v1/components?repository=$REPO" 2>&1)
        
        HTTP_CODE=$(echo "$RESPONSE" | tail -n 1)
        BODY=$(echo "$RESPONSE" | head -n -1)
        
        if [ "$HTTP_CODE" -eq 201 ] || [ "$HTTP_CODE" -eq 204 ]; then
          echo "Successfully uploaded artifact to Nexus"
          echo "Artifact URL: $NEXUS_URL/repository/$REPO/$GROUP_ID/$ARTIFACT_ID/$VERSION/"
        elif [ "$HTTP_CODE" -eq 401 ] || [ "$HTTP_CODE" -eq 403 ]; then
          echo "Authentication failed. Trying Nexus 2.x format..."
          # Try Nexus 2.x format
          RESPONSE2=$(curl -s -w "\n%{http_code}" \
            -u "$USERNAME:$PASSWORD" \
            -X POST \
            -F "r=$REPO" \
            -F "hasPom=false" \
            -F "e=$PACKAGING" \
            -F "g=$GROUP_ID" \
            -F "a=$ARTIFACT_ID" \
            -F "v=$VERSION" \
            -F "p=$PACKAGING" \
            -F "file=@$ARTIFACT_FILE" \
            "$NEXUS_URL/service/local/artifact/maven/content" 2>&1)
          
          HTTP_CODE2=$(echo "$RESPONSE2" | tail -n 1)
          if [ "$HTTP_CODE2" -eq 201 ] || [ "$HTTP_CODE2" -eq 200 ]; then
            echo "Successfully uploaded artifact to Nexus 2.x"
            echo "Artifact URL: $NEXUS_URL/repository/$REPO/$GROUP_ID/$ARTIFACT_ID/$VERSION/"
          else
            echo "Error uploading to Nexus 2.x: HTTP $HTTP_CODE2"
            echo "$RESPONSE2" | head -n -1
            exit 1
          fi
        else
          echo "Error uploading to Nexus: HTTP $HTTP_CODE"
          echo "$BODY"
          exit 1
        fi
      env:
        - name: NEXUS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nexus-credentials
              key: password

