# Example PipelineRun - Not managed by GitOps
# PipelineRuns are typically created manually or via triggers
# This file is for reference only

apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: dotnet-demo-pipeline-run
  namespace: dotnet-demo
  labels:
    app: dotnet-demo
    app.kubernetes.io/name: dotnet-demo
    app.kubernetes.io/component: pipeline
    tekton.dev/pipeline: dotnet-demo-pipeline
spec:
  pipelineRef:
    name: dotnet-demo-pipeline
  params:
    - name: git-url
      value: "https://gitlab.com/maximilianoPizarro/connectivity-link.git"
    - name: git-revision
      value: "main"
    - name: nexus-url
      value: "http://nexus-nexus2.apps.cluster-gpzvq.gpzvq.sandbox670.opentlc.com"
    - name: nexus-repository
      value: "releases"
    - name: nexus-username
      value: "admin"
    - name: nexus-group-id
      value: "com.example"
    - name: nexus-artifact-id
      value: "dotnet-demo"
    - name: nexus-version
      value: "1.0.0"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: cache
      persistentVolumeClaim:
        claimName: dotnet-demo-cache

