apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: dotnet-demo-pipeline
  namespace: dotnet-demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: dotnet-demo
    app.kubernetes.io/name: dotnet-demo
    app.kubernetes.io/component: pipeline
spec:
  params:
    - name: git-url
      description: Git repository URL
      type: string
      default: "https://gitlab.com/maximilianoPizarro/connectivity-link.git"
    - name: git-revision
      description: Git revision (branch, tag, or commit)
      type: string
      default: "main"
    - name: nexus-url
      description: Nexus repository URL
      type: string
      default: "http://nexus-nexus2.apps.cluster-gpzvq.gpzvq.sandbox670.opentlc.com"
    - name: nexus-repository
      description: Nexus repository name
      type: string
      default: "releases"
    - name: nexus-username
      description: Nexus username
      type: string
      default: "admin"
    - name: nexus-group-id
      description: Maven group ID
      type: string
      default: "com.example"
    - name: nexus-artifact-id
      description: Maven artifact ID
      type: string
      default: "dotnet-demo"
    - name: nexus-version
      description: Artifact version
      type: string
      default: "1.0.0"
  workspaces:
    - name: source
      description: Source code workspace
    - name: cache
      description: Build cache workspace
  tasks:
    - name: clone-repo
      taskRef:
        apiVersion: tekton.dev/v1
        kind: Task
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: source

    - name: build-dotnet
      runAfter:
        - clone-repo
      taskRef:
        apiVersion: tekton.dev/v1
        kind: Task
        name: s2i-dotnet
      params:
        - name: VERSION
          value: "8.0"
        - name: OUTPUT_IMAGE
          value: "image-registry.openshift-image-registry.svc:5000/dotnet-demo/dotnet-demo:latest"
      workspaces:
        - name: source
          workspace: source

    - name: build-nuget-package
      runAfter:
        - build-dotnet
      taskRef:
        apiVersion: tekton.dev/v1
        kind: Task
        name: dotnet-build-nuget
      params:
        - name: PROJECT_PATH
          value: "dotnet-demo/src"
        - name: VERSION
          value: $(params.nexus-version)
      workspaces:
        - name: source
          workspace: source
        - name: cache
          workspace: cache

    - name: publish-to-nexus
      runAfter:
        - build-nuget-package
      taskRef:
        apiVersion: tekton.dev/v1
        kind: Task
        name: nexus-upload
      params:
        - name: NEXUS_URL
          value: $(params.nexus-url)
        - name: NEXUS_REPOSITORY
          value: $(params.nexus-repository)
        - name: NEXUS_USERNAME
          value: $(params.nexus-username)
        - name: GROUP_ID
          value: $(params.nexus-group-id)
        - name: ARTIFACT_ID
          value: $(params.nexus-artifact-id)
        - name: VERSION
          value: $(params.nexus-version)
        - name: PACKAGING
          value: "nupkg"
        - name: FILE_PATH
          value: "dotnet-demo/src/bin/Release/*.nupkg"
      workspaces:
        - name: source
          workspace: source

