apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: neuralbank-stack
  description: NeuralBank demo application stack - Full-stack application with frontend, backend, database, and proxy
  annotations:
    backstage.io/view-url: https://neuralbank.apps.cluster-gpzvq.gpzvq.sandbox670.opentlc.com
    argocd/app-name: neuralbank-stack
    argocd/app-namespace: openshift-gitops
    # ArgoCD URL - Update with your cluster domain
    # Format: https://openshift-gitops-server-openshift-gitops.apps.<cluster-domain>/applications/neuralbank-stack
    argocd/app-url: https://openshift-gitops-server-openshift-gitops.apps.cluster-gpzvq.gpzvq.sandbox670.opentlc.com/applications/neuralbank-stack
    gitlab.com/project-slug: maximilianoPizarro/connectivity-link
  tags:
    - neuralbank
    - demo-app
    - full-stack
    - postgresql
    - helm
    - frontend
    - backend
spec:
  type: service
  lifecycle: production
  owner: application-team
  system: neuralbank-system
  providesApis:
    - neuralbank-api
  consumesApis:
    - keycloak-api
  dependsOn:
    - component:rhbk/keycloak
    - component:rhcl-operator/gateway
    - component:servicemeshoperator3/istio-gateway

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: neuralbank-backend
  description: NeuralBank backend API service
  annotations:
    argocd/app-name: neuralbank-stack
    argocd/app-namespace: openshift-gitops
spec:
  type: service
  lifecycle: production
  owner: application-team
  system: neuralbank-system
  providesApis:
    - neuralbank-api

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: neuralbank-frontend
  description: NeuralBank frontend web application
  annotations:
    argocd/app-name: neuralbank-stack
    argocd/app-namespace: openshift-gitops
spec:
  type: website
  lifecycle: production
  owner: application-team
  system: neuralbank-system

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: neuralbank-database
  description: NeuralBank PostgreSQL database
  annotations:
    argocd/app-name: neuralbank-stack
    argocd/app-namespace: openshift-gitops
spec:
  type: database
  lifecycle: production
  owner: application-team
  system: neuralbank-system

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: neuralbank-api
  description: NeuralBank REST API
spec:
  type: rest
  lifecycle: production
  owner: application-team
  definition: |
    openapi: "3.0.0"
    info:
      title: NeuralBank API
      version: "1.0.0"
    paths:
      /api:
        get:
          summary: Get API data
      /q:
        get:
          summary: Query endpoint

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: neuralbank-system
  description: NeuralBank application system
spec:
  owner: application-team
  domain: banking

