apiVersion: v1
kind: Service
metadata:
  name: workshop-pipelines-db
  namespace: workshop-pipelines
  labels:
    app: workshop-pipelines-db
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: workshop-pipelines-db

