---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workshop-pipelines-gitops-clusterrole
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups:
      - helm.openshift.io
    resources:
      - helmchartrepositories
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups:
      - "" 
    resources:
      - services
      - secrets
      - serviceaccounts
      - configmaps
      - pods
      - persistentvolumeclaims
      - events
      - namespaces
    verbs:
      - "*"

  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - replicasets
    verbs:
      - "*"

  - apiGroups:
      - networking.k8s.io
      - policy
    resources:
      - networkpolicies
      - poddisruptionbudgets
      - ingresses
    verbs:
      - "*"

  - apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs:
      - "*"
      
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workshop-pipelines-gitops-clusterrolebinding
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workshop-pipelines-gitops-clusterrole
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-application-controller
    namespace: openshift-gitops
  - kind: ServiceAccount
    name: argocd-argocd-applicationset-controller
    namespace: openshift-gitops

