---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workshop-pipelines-postgresql
  namespace: workshop-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workshop-pipelines-postgresql-anyuid
  namespace: workshop-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: workshop-pipelines-postgresql
    namespace: workshop-pipelines

