---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workshop-pipelines-gitops-clusterrole
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
  - apiGroups:
      - helm.openshift.io
    resources:
      - helmchartrepositories
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "" 
    resources:
      - services
      - secrets
      - serviceaccounts
      - configmaps
      - pods
      - persistentvolumeclaims
      - events
      - namespaces
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - replicasets
    verbs:
      - "*"
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
      - ingresses
    verbs:
      - "*"
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - "*"
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs:
      - "*"
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - "*"
  - apiGroups:
      - tekton.dev
    resources:
      - pipelines
      - pipelineruns
      - tasks
      - taskruns
    verbs:
      - "*"
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggertemplates
      - triggerbindings
    verbs:
      - "*"
  - apiGroups:
      - build.openshift.io
    resources:
      - buildconfigs
    verbs:
      - "*"
  - apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workshop-pipelines-gitops-clusterrolebinding
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workshop-pipelines-gitops-clusterrole
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
  - kind: ServiceAccount
    name: openshift-gitops-argocd-applicationset-controller
    namespace: openshift-gitops

