apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workshop-pipelines-db-pvc
  namespace: workshop-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

