# ------------------------------------------------------------
# KeycloakRealmImport: Importa todo el Realm (configuración y usuarios)
# ------------------------------------------------------------
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: neuralbank-full-import-from-json
  namespace: rhbk-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  keycloakCRName: rhbk
  realm:
    id: neuralbank
    realm: neuralbank
    enabled: true
    displayName: NeuralBank IA
    displayNameHtml: Connectivity Link
    notBefore: 0
    accessTokenLifespan: 300
    ssoSessionIdleTimeout: 1800
    ssoSessionMaxLifespan: 36000
    offlineSessionIdleTimeout: 2592000
    offlineSessionMaxLifespanEnabled: false
    offlineSessionMaxLifespan: 5184000
    accessCodeLifespan: 60
    sslRequired: none
    registrationAllowed: false
    rememberMe: false
    verifyEmail: false
    loginWithEmailAllowed: true
    duplicateEmailsAllowed: false
    resetPasswordAllowed: false
    bruteForceProtected: false
    
    clients:
    - clientId: neuralbank-frontend
      name: Frontend Web App
      publicClient: false
      standardFlowEnabled: true
      redirectUris: 
      - "https://librechat-librechat-librechat.apps.cluster-wmdrk.wmdrk.sandbox2484.opentlc.com/*"
      - "https://neuralbank.apps.cluster-wmdrk.wmdrk.sandbox2484.opentlc.com/*"
      - "https://librechat-librechat-librechat.apps.cluster-wmdrk.wmdrk.sandbox2484.opentlc.com/oauth/openid/callback"
      webOrigins: ["*"]
      bearerOnly: false
      secret: "**********"
      directAccessGrantsEnabled: true
      fullScopeAllowed: true
    - clientId: neuralbank-backend
      name: Backend API Service
      publicClient: false
      bearerOnly: true
      secret: "**********"
      fullScopeAllowed: true
    - clientId: neuralbank
      name: Neural Bank IA
      baseUrl: "http://neuralbank.apps.cluster-wmdrk.wmdrk.sandbox2484.opentlc.com"
      enabled: true
      clientAuthenticatorType: client-secret
      secret: "**********"
      redirectUris:
      - "https://neuralbank.apps.cluster-wmdrk.wmdrk.sandbox2484.opentlc.com/auth/callback"
      - "https://localhost:8080/*"
      webOrigins: ["*"]
      bearerOnly: false
      standardFlowEnabled: true
      directAccessGrantsEnabled: true
      publicClient: false
      frontchannelLogout: true
      fullScopeAllowed: true
    - clientId: realm-management
      name: "${client_realm-management}"
      enabled: true
      clientAuthenticatorType: client-secret
      bearerOnly: true
      publicClient: false
      fullScopeAllowed: false
    - clientId: account
      name: "${client_account}"
      baseUrl: "/realms/neuralbank/account/"
      enabled: true
      clientAuthenticatorType: client-secret
      redirectUris: ["/realms/neuralbank/account/*"]
      bearerOnly: false
      standardFlowEnabled: true
      publicClient: true
      fullScopeAllowed: false
    - clientId: account-console
      name: "${client_account-console}"
      baseUrl: "/realms/neuralbank/account/"
      enabled: true
      clientAuthenticatorType: client-secret
      redirectUris: ["/realms/neuralbank/account/*"]
      bearerOnly: false
      standardFlowEnabled: true
      publicClient: true
      fullScopeAllowed: false
    - clientId: admin-cli
      name: "${client_admin-cli}"
      enabled: true
      clientAuthenticatorType: client-secret
      bearerOnly: false
      standardFlowEnabled: false
      directAccessGrantsEnabled: true
      publicClient: true
      fullScopeAllowed: true
    - clientId: broker
      name: "${client_broker}"
      enabled: true
      clientAuthenticatorType: client-secret
      bearerOnly: true
      publicClient: false
      fullScopeAllowed: false
    - clientId: security-admin-console
      name: "${client_security-admin-console}"
      baseUrl: "/admin/neuralbank/console/"
      enabled: true
      clientAuthenticatorType: client-secret
      redirectUris: ["/admin/neuralbank/console/*"]
      webOrigins: ["+"]
      bearerOnly: false
      standardFlowEnabled: true
      publicClient: true
      fullScopeAllowed: true
      
    groups:
    - name: US-Clients
    - name: LATAM-Clients
    - name: EU-Clients
    
    realmRoles:
    - name: personal-client
    - name: corporate-client
    - name: offline_access
    - name: uma_authorization
    - name: default-roles-neuralbank
      composite: true
      composites:
        realm:
        - offline_access
        - uma_authorization
        client:
          account:
          - manage-account
          - view-profile

    users:
    # --- Clientes USA ---
    - username: robert.anderson@email.com
      email: robert.anderson@email.com
      firstName: Robert
      lastName: Anderson
      enabled: true
      groups: ["US-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: jennifer.martinez@email.com
      email: jennifer.martinez@email.com
      firstName: Jennifer
      lastName: Martinez
      enabled: true
      groups: ["US-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: david.lee@email.com
      email: david.lee@email.com
      firstName: David
      lastName: Lee
      enabled: true
      groups: ["US-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: michelle.garcia@email.com
      email: michelle.garcia@email.com
      firstName: Michelle
      lastName: Garcia
      enabled: true
      groups: ["US-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: contact@techcorp.com
      email: contact@techcorp.com
      firstName: TechCorp
      lastName: Solutions Inc
      enabled: true
      groups: ["US-Clients"]
      realmRoles: ["corporate-client"]
      initialPassword: { value: "Welcome123", temporary: true }

    # --- Clientes México/LATAM ---
    - username: mario.gomez@email.com
      email: mario.gomez@email.com
      firstName: Mario
      lastName: Gómez Morales
      enabled: true
      groups: ["LATAM-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: laura.martinez@email.com
      email: laura.martinez@email.com
      firstName: Laura
      lastName: Martínez Pérez
      enabled: true
      groups: ["LATAM-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: carlos.sanchez.mex@email.com
      email: carlos.sanchez.mex@email.com
      firstName: Carlos
      lastName: Sánchez Muñoz
      enabled: true
      groups: ["LATAM-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: paulo.silva@email.com
      email: paulo.silva@email.com
      firstName: Paulo
      lastName: Silva Santos
      enabled: true
      groups: ["LATAM-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: ricardo.ferreira@email.com
      email: ricardo.ferreira@email.com
      firstName: Ricardo
      lastName: Ferreira Lima
      enabled: true
      groups: ["LATAM-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: diego.martinez.ar@email.com
      email: diego.martinez.ar@email.com
      firstName: Diego
      lastName: Martínez Suárez
      enabled: true
      groups: ["LATAM-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: lucia.fernandez@email.com
      email: lucia.fernandez@email.com
      firstName: Lucía
      lastName: Fernández Gómez
      enabled: true
      groups: ["LATAM-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: juan.perez@email.com
      email: juan.perez@email.com
      firstName: Juan
      lastName: Pérez González
      enabled: true
      groups: ["LATAM-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: maria.silva@email.com
      email: maria.silva@email.com
      firstName: María
      lastName: Silva Rojas
      enabled: true
      groups: ["LATAM-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: info@comercializadora.mx
      email: info@comercializadora.mx
      firstName: Comercializadora
      lastName: Global SA de CV
      enabled: true
      groups: ["LATAM-Clients"]
      realmRoles: ["corporate-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: contacto@constructora.ar
      email: contacto@constructora.ar
      firstName: Constructora
      lastName: del Sur SRL
      enabled: true
      groups: ["LATAM-Clients"]
      realmRoles: ["corporate-client"]
      initialPassword: { value: "Welcome123", temporary: true }

    # --- Clientes Europa/Reino Unido ---
    - username: antonio.garcia@email.com
      email: antonio.garcia@email.com
      firstName: Antonio
      lastName: García López
      enabled: true
      groups: ["EU-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: carmen.martin@email.com
      email: carmen.martin@email.com
      firstName: Carmen
      lastName: Martín Sánchez
      enabled: true
      groups: ["EU-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: javier.rodriguez@email.com
      email: javier.rodriguez@email.com
      firstName: Javier
      lastName: Rodríguez Torres
      enabled: true
      groups: ["EU-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: william.johnson@email.com
      email: william.johnson@email.com
      firstName: William
      lastName: Johnson
      enabled: true
      groups: ["EU-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: sophie.thompson@email.com
      email: sophie.thompson@email.com
      firstName: Sophie
      lastName: Thompson
      enabled: true
      groups: ["EU-Clients"]
      realmRoles: ["personal-client"]
      initialPassword: { value: "Welcome123", temporary: true }
    - username: info@inversionesmadrid.es
      email: info@inversionesmadrid.es
      firstName: Inversiones
      lastName: Madrid SA
      enabled: true
      groups: ["EU-Clients"]
      realmRoles: ["corporate-client"]
      initialPassword: { value: "Welcome123", temporary: true }

    # Secciones adicionales del JSON para una configuración más completa (opcional, pero se mantiene la estructura)
    authenticationFlows:
    - id: 5e770a4d-1398-45df-a7c0-4da8ce42eba1
      alias: browser
      description: Browser based authentication
      providerId: basic-flow
      topLevel: true
      builtIn: true
      authenticationExecutions:
      - authenticator: auth-cookie
        authenticatorFlow: false
        requirement: ALTERNATIVE
        priority: 10
      - authenticator: auth-spnego
        authenticatorFlow: false
        requirement: DISABLED
        priority: 20
      - authenticator: identity-provider-redirector
        authenticatorFlow: false
        requirement: ALTERNATIVE
        priority: 25
      - authenticatorFlow: true
        requirement: ALTERNATIVE
        priority: 26
        flowAlias: Organization
      - authenticatorFlow: true
        requirement: ALTERNATIVE
        priority: 30
        flowAlias: forms
    