# Headless Service required by StatefulSet for pod identity (pod-0.postgresql-db-service.namespace.svc)
apiVersion: v1
kind: Service
metadata:
  name: postgresql-db-service
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  clusterIP: None
  selector:
    app: postgresql-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:15
          volumeMounts:
            - mountPath: /data
              name: cache-volume
          env:
            - name: POSTGRES_USER
              value: testuser
            - name: POSTGRES_PASSWORD
              value: testpassword
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_DB
              value: keycloak
      volumes:
        - name: cache-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  selector:
    app: postgresql-db
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432