# HTPasswd secret for OpenShift OAuth (openshift-config).
# Replace the htpasswd data with your own: echo -n 'user:$2y$10$...' | base64 -w0
# Generate: htpasswd -cb - admin yourpassword | base64 -w0
apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
  # admin / password (change in production). Generate: htpasswd -cb - admin <pass> | base64 -w0
  htpasswd: YWRtaW46JDJhJDEwJE45cW84dUxPaWNrZ3gyWk1SWm9NeWVJalphZ2NmbDdwOTJsZEd4YWQ2OExKWmRMMTdsaFd5
