# OAuth cluster config: HTPasswd identity provider.
# WARNING: Applying this replaces the cluster's OAuth spec.identityProviders with only this entry.
# If the cluster already has other IDPs (e.g. KubeAdmin, LDAP), merge them manually or use a patch.
# See README for adding to existing OAuth without replacing.
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  identityProviders:
    - name: htpasswd
      mappingMethod: claim
      type: HTPasswd
      htpasswd:
        fileData:
          name: htpasswd-secret
