apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic-install
  annotations:
    argocd.argoproj.io/sync-wave: "3" 
spec:
  version: v2.5
  tracing:
    type: None
  profiles:
    - default 
  gateways:
    openshiftIngress: true 
    ingress:
      enabled: true
      service:
        type: LoadBalancer

  addons:
    grafana:
      enabled: false
    kiali:
      enabled: false
    prometheus:
      enabled: false
