kind: Istio
apiVersion: sailoperator.io/v1
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  namespace: istio-system
  updateStrategy:
    inactiveRevisionDeletionGracePeriodSeconds: 30
    type: InPlace
  version: v1.27.3