apiVersion: install.istio.io/v1alpha1
kind: Istio
metadata:
  name: basic-install
  annotations:
    argocd.argoproj.io/sync-wave: "3" 
spec:
  profile: default
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            type: LoadBalancer
    pilot:
      enabled: true
  
  values:
    gateways:
      istio-ingressgateway:
        externalTrafficPolicy: Local