---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workshop-pipelines-gitops-clusterrole
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
  # Permisos para Helm Chart Repository
  - apiGroups:
      - helm.openshift.io
    resources:
      - helmchartrepositories
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Permisos para CatalogSources (necesario para crear redhat-operators)
  - apiGroups:
      - operators.coreos.com
    resources:
      - catalogsources
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Permisos para crear namespaces (necesario para CreateNamespace=true)
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
      - get
      - list
      - watch
  # Permisos para crear Roles y RoleBindings (necesario para aplicar el RoleBinding)
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Permisos para CustomResourceDefinitions (incluyendo eliminación para sincronización)
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # Permisos para CheCluster resources (DevSpaces)
  - apiGroups:
      - org.eclipse.che
    resources:
      - checlusters
      - checlusters/status
      - checlusters/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workshop-pipelines-gitops-clusterrolebinding
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workshop-pipelines-gitops-clusterrole
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
  - kind: ServiceAccount
    name: openshift-gitops-argocd-applicationset-controller
    namespace: openshift-gitops

