apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: rhbk-operator
  namespace: rhbk-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  targetNamespaces:
    - rhbk-operator
