---
# Root group - all teams are children of this group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
  description: Root organization group for Developer Hub
spec:
  type: organization
  profile:
    displayName: Developer Hub Organization
    email: admin@developer-hub.local
  children:
    - developers
    - devteam1
    - infrastructure
    - platformengineers
    - rhdh
    - platform-team
    - application-team

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: developers
  description: General developers team
  annotations:
    # Keycloak group path - this helps the provider sync members
    keycloak.org/group-path: /developers
spec:
  type: team
  profile:
    displayName: Developers
    email: developers@developer-hub.local
  parent: backstage
  children: []
  # Members are automatically synced from Keycloak by the keycloakOrg provider
  # Do not specify members manually here

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: devteam1
  description: Development Team 1
  annotations:
    keycloak.org/group-path: /devteam1
spec:
  type: team
  profile:
    displayName: Dev Team 1
    email: devteam1@developer-hub.local
  parent: backstage
  children: []
  # Members are automatically synced from Keycloak by the keycloakOrg provider

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infrastructure
  description: Infrastructure team responsible for infrastructure management
  annotations:
    keycloak.org/group-path: /infrastructure
spec:
  type: team
  profile:
    displayName: Infrastructure Team
    email: infrastructure@developer-hub.local
  parent: backstage
  children: []
  # Members are automatically synced from Keycloak by the keycloakOrg provider

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platformengineers
  description: Platform engineering team responsible for infrastructure, authentication, and developer tools
  annotations:
    keycloak.org/group-path: /platformengineers
spec:
  type: team
  profile:
    displayName: Platform Engineers
    email: platformengineers@developer-hub.local
  parent: backstage
  children: []
  # Members are automatically synced from Keycloak by the keycloakOrg provider

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: rhdh
  description: Red Hat Developer Hub team
  annotations:
    keycloak.org/group-path: /rhdh
spec:
  type: team
  profile:
    displayName: RHDH Team
    email: rhdh@developer-hub.local
  parent: backstage
  children: []
  # Members are automatically synced from Keycloak by the keycloakOrg provider

---
# Legacy groups - mapped to Keycloak groups for synchronization
# platform-team maps to platformengineers group in Keycloak
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Platform engineering team responsible for infrastructure, authentication, and developer tools
  annotations:
    # Map to platformengineers group in Keycloak for user synchronization
    keycloak.org/group-path: /platformengineers
spec:
  type: team
  profile:
    displayName: Platform Team
    email: platform-team@developer-hub.local
  parent: backstage
  children: []
  # Members are automatically synced from Keycloak platformengineers group
  # Members: user7-platform, user8-platform

---
# Legacy group - mapped to developers group in Keycloak
# application-team maps to developers group in Keycloak
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: application-team
  description: Application development team responsible for business applications
  annotations:
    # Map to developers group in Keycloak for user synchronization
    keycloak.org/group-path: /developers
spec:
  type: team
  profile:
    displayName: Application Team
    email: application-team@developer-hub.local
  parent: backstage
  children: []
  # Members are automatically synced from Keycloak developers group
  # Members: user1-dev, user2-dev

