---
# User entities for Backstage catalog
# Users are typically created automatically when they first authenticate,
# but explicit definitions ensure they appear in the catalog and can be referenced

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: maximilianopizarro
  description: Maximiliano Pizarro - Platform Engineer and Administrator
spec:
  profile:
    displayName: Maximiliano Pizarro
    email: maximiliano.pizarro.5@gmail.com
    picture: https://github.com/maximilianoPizarro.png
  memberOf:
    - platform-team
    - platformengineers
    - rhdh

