---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "librechat.fullname" . }}-mongodb-anyuid-binding
  namespace: {{ .Values.librechat.namespace | default .Release.Namespace }}
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-mongodb
    namespace: {{ .Values.librechat.namespace | default .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "librechat.fullname" . }}-mongodb-default-anyuid-binding
  namespace: {{ .Values.librechat.namespace | default .Release.Namespace }}
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.librechat.namespace | default .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid

