---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: devworkspace-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: latest
  installPlanApproval: Automatic
  name: devworkspace-operator
  startingCSV: devworkspace-operator.v0.38.0
  source: redhat-operators
  sourceNamespace: openshift-marketplace