---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kuadrant-operator
  namespace: kuadrant-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: stable
  name: kuadrant-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace