---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: latest 
  installPlanApproval: Automatic
  startingCSV: openshift-pipelines-operator-rh.v1.20.1
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace