apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: rhbk-operator
  namespace: rhbk-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  targetNamespaces:
    - rhbk-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhbk-operator
  namespace: rhbk-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: stable-v26.2
  startingCSV: rhbk-operator.v26.2.11-opr.1
  installPlanApproval: Automatic
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace