apiVersion: v1
kind: Namespace
metadata:
  name: rhdh-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    operators.coreos.com/rhdh-operator.rhdh-operator: ""
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: rhdh-operator
  namespace: rhdh-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhdh-operator
  namespace: rhdh-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: fast
  startingCSV: rhdh-operator.v1.8.0
  installPlanApproval: Automatic
  name: rhdh
  source: redhat-operators
  sourceNamespace: openshift-marketplace