# Replace placeholder values before deploy. Optional: run ./preparation.sh (after setting user-values.env) to overwrite from template.
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: backend
    component: api
type: Opaque
stringData:
  database-url: postgresql://litemaas_admin:change-me-pg-password@postgres:5432/litemaas_db?sslmode=disable
  jwt-secret: change-me-jwt-secret
  oauth-client-id: litemaas-oauth-client
  oauth-client-secret: change-me-oauth-secret
  admin-api-keys: change-me-admin-key
  litellm-api-key: sk-change-me-litellm-admin-key
