# Replace placeholders before deploy. Optional: run ./preparation.sh (after setting user-values.env) to overwrite from template.
apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
  labels:
    app: litellm
    component: ai-proxy
type: Opaque
stringData:
  database-url: postgresql://litemaas_admin:change-me-pg-password@postgres:5432/litellm_db
  master-key: sk-change-me-litellm-admin-key
  ui-username: admin
  ui-password: change-me-ui-password
