# Replace placeholder before deploy. Optional: run ./preparation.sh (after setting user-values.env) to overwrite from template.
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
    component: database
type: Opaque
stringData:
  username: litemaas_admin
  password: change-me-pg-password
