# RateLimitPolicy on the Gateway (same namespace as gateway so Kuadrant injects it).
# Limit set for normal web use (page load = many requests). Adjust as needed.
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: litemaas-gateway-ratelimit
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: litemaas-gateway
  limits:
    chat-global:
      rates:
        - limit: 120
          window: 1m
