# RateLimitPolicy for LiteMaaS HTTPRoute (global for this route).
# Limit set for normal web use; adjust as needed. Not in kustomization by default.
#
# IMPORTANT: The limit is enforced only when traffic goes through the Gateway API
# (litemaas-gateway in istio-system). If you use an OpenShift Route that points
# directly to the frontend/backend service, traffic bypasses the gateway and this
# policy never runs. Ensure the host (e.g. litemaas.apps.<domain>) is served by
# the Istio gateway, not by a direct Route to the app services.
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: litemaas-ratelimit
  namespace: litemaas
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: litemaas-route
    namespace: litemaas
  limits:
    chat-global:
      rates:
        - limit: 120
          window: 1m
