# RateLimitPolicy on the Gateway (same namespace as gateway so Kuadrant injects it).
# Requires Limitador and kuadrant-ratelimit-service reachable (e.g. in kuadrant-system or istio-system).
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: litemaas-gateway-ratelimit
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: litemaas-gateway
  limits:
    chat-global:
      rates:
        - limit: 2
          window: 1m
