# Role and RoleBinding so Argo CD (openshift-gitops / Connectivity Link) can create/update resources in the litemaas namespace.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: litemaas-gitops-role
  namespace: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: [""]
    resources:
      - serviceaccounts
      - secrets
      - services
      - pods
      - configmaps
      - events
      - persistentvolumeclaims
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - replicasets
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: ["route.openshift.io"]
    resources: [routes]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - gateways
      - httproutes
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
    verbs: [create, delete, get, list, patch, update, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: litemaas-gitops-rolebinding
  namespace: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: Role
  name: litemaas-gitops-role
  apiGroup: rbac.authorization.k8s.io
