# TokenRateLimitPolicy for LiteMaaS gateway (same namespace as gateway).
apiVersion: kuadrant.io/v1alpha1
kind: TokenRateLimitPolicy
metadata:
  name: token-limit-litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  limits:
    free:
      rates:
        - limit: 60
          window: 1m
    gold:
      counters:
        - expression: auth.identity.userid
      rates:
        - limit: 200000
          window: 24h
      when:
        - predicate: 'request.auth.claims["kuadrant.io/groups"].split(",").exists(g, g == "gold")'
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: litemaas-gateway
