---
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: openshift-devspaces
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  # Configuración de componentes
  components:
    # Configuración del servidor Che
    cheServer:
      extraProperties:
        # Configuración de recursos por defecto para workspaces (sin límites estrictos)
        CHE_WORKSPACE_DEFAULT__CPU__REQUEST: "1"
        CHE_WORKSPACE_DEFAULT__CPU__LIMIT: ""
        CHE_WORKSPACE_DEFAULT__MEMORY__REQUEST: "2Gi"
        CHE_WORKSPACE_DEFAULT__MEMORY__LIMIT: ""
        CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST: "100m"
        CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__LIMIT: ""
        CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__REQUEST: "128Mi"
        CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT: ""
        # Deshabilitar límites de recursos para workspaces
        CHE_WORKSPACE_DEFAULT__RESOURCE__LIMITS__CPU: ""
        CHE_WORKSPACE_DEFAULT__RESOURCE__LIMITS__MEMORY: ""
        CHE_WORKSPACE_DEFAULT__RESOURCE__REQUESTS__CPU: "1"
        CHE_WORKSPACE_DEFAULT__RESOURCE__REQUESTS__MEMORY: "2Gi"
      debug: false
      logLevel: INFO
      # Configuración de recursos del servidor Che
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
    
    # Configuración de la base de datos
    database:
      externalDb: false
      postgresHostName: ""
      postgresPort: ""
      postgresUser: ""
      postgresPassword: ""
      postgresDb: "dbche"
      credentialsSecretName: "postgres-credentials"
      pvc:
        claimSize: "10Gi"
        storageClass: ""
    
    # Configuración de métricas
    metrics:
      enable: true
    
    # Configuración del dashboard
    dashboard:
      enable: true
    
    # Configuración de DevWorkspace
    devWorkspace:
      enable: true
      # Sin límite de workspaces en ejecución
      runningLimit: ""
      secondsOfInactivityBeforeIdling: 1800
      secondsOfRunBeforeIdling: -1
      # Editor por defecto
      defaultEditor: "che-incubator/che-code/insiders"
      # Componentes por defecto sin límites de recursos
      defaultComponents:
        - name: universal-developer-image
          container:
            image: quay.io/devfile/universal-developer-image:ubi8-latest
            # Sin límites de recursos
            memoryRequest: "1Gi"
            memoryLimit: ""
            cpuRequest: "500m"
            cpuLimit: ""
  
  # Configuración de networking
  networking:
    hostname: ""
    tlsSupport: true
    auth:
      gateway:
        configLabels:
          app: che
          component: che-gateway-config
  
  # Configuración de Git
  gitServices:
    github:
      endpoint: ""
    gitlab:
      endpoint: ""
    bitbucket:
      endpoint: ""
    azureDevOps:
      endpoint: ""
  
  # Configuración de storage
  storage:
    pvcStrategy: "per-workspace"
    pvcClaimSize: "10Gi"
    preCreateSubPaths: true
  
  # Configuración de container registry
  containerRegistry:
    hostname: ""
    organization: ""
  
  # Configuración de devfile registry
  devfileRegistry:
    disableInternalRegistry: false
    externalDevfileRegistries:
      - url: "https://registry.devfile.io"
  
  # Configuración de plugin registry
  pluginRegistry:
    disableInternalRegistry: false
    externalPluginRegistries:
      - url: "https://registry.redhat.io"
  
  # Configuración de image pull secrets
  imagePuller:
    enable: false
    spec: {}
  
  # Configuración de server
  server:
    cheFlavor: "devspaces"
    allowAutoProvision: true
    allowUserDefinedWorkspaceNamespaces: true
    workspaceNamespaces:
      - "<username>-devspaces"

