apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: openshift-devspaces
  labels:
    app.kubernetes.io/instance: devspaces
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  components:
    cheServer:
      debug: false
      # metrics:
      #   enabled: true
  devEnvironments:
    defaultNamespace:
      autoProvision: true
      template: "<username>-devspaces"
    defaultComponents:
      - name: universal-developer-image
        container:
          image: registry.redhat.io/devspaces/udi-rhel9:latest
          memoryLimit: "4Gi"
          memoryRequest: "512Mi"
    defaultEditor: che-code/latest
    containerSecurityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
          - SETGID
          - SETUID
    disableContainerBuildCapabilities: false
    secondsOfInactivityBeforeIdling: 1800
    storage:
      pvcStrategy: per-user