apiVersion: v1
kind: Namespace
metadata:
  name: kuadrant-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhbk-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhdh-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    operators.coreos.com/rhdh-operator.rhdh-operator: ""
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: neuralbank-stack
  annotations:
    argocd.argoproj.io/sync-wave: "1"