apiVersion: v1
kind: Namespace
metadata:
  name: patch-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhbk-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhdh-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    operators.coreos.com/rhdh.rhdh-operator: ""