apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
      mountPath: /opt/app-root/src # This mounts the Backstage config for Backstage itself
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    extraEnvs:
      secrets:
        - name: secrets-rhdh
        - name: lightspeed-secrets
    extraFiles:
      configMaps:
        - name: rhdh-rbac-policy
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
  deployment:
    patch:
      spec:
        template:
          spec:
            initContainers:
              - name: init-rag-data
                image: 'quay.io/redhat-ai-dev/rag-content:release-1.8-lcs'
                command:
                  - "sh"
                  - "-c"
                  - "echo 'Copying RAG data...'; cp -r /rag/vector_db/rhdh_product_docs /data/ && cp -r /rag/embeddings_model /data/ && echo 'Copy complete.'"
                volumeMounts:
                  - mountPath: /data
                    name: rag-data-volume
            containers:
              - envFrom:
                  - secretRef:
                      name: llama-stack-secrets
                env:
                  - name: MCP_HEADERS
                    value: '{"backstage-actions": {"Authorization": "Bearer backstage"}, "http://localhost:7007/api/mcp-actions/v1": {"Authorization": "Bearer backstage"}, "http://localhost:7007/api/mcp-actions/v1/sse": {"Authorization": "Bearer backstage"}}'
                image: 'quay.io/redhat-ai-dev/llama-stack:0.1.1'
                name: llama-stack
                ports:
                  - containerPort: 8321
                    name: llama-stack-api
                    protocol: TCP
                readinessProbe:
                  tcpSocket:
                    port: 8321
                  initialDelaySeconds: 15
                  periodSeconds: 5
                  timeoutSeconds: 3
                  successThreshold: 1
                  failureThreshold: 3
                startupProbe:
                  tcpSocket:
                    port: 8321
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 3
                  successThreshold: 1
                  failureThreshold: 20
                volumeMounts:
                  - mountPath: /app-root/.llama
                    name: shared-storage
                  - mountPath: /app-root/embeddings_model
                    name: rag-data-volume
                    subPath: embeddings_model
                  - mountPath: /app-root/vector_db/rhdh_product_docs
                    name: rag-data-volume
                    subPath: rhdh_product_docs
                  - mountPath: /app-root/run.yaml
                    name: llama-stack-config
                    subPath: run.yaml
              # Pin to 0.2.x image: latest uses llama_stack_client 0.4.3, incompatible with llama-stack:0.1.1 (server 0.2.18)
              - image: 'quay.io/lightspeed-core/lightspeed-stack:0.2.0'
                name: lightspeed-core
                envFrom:
                  - secretRef:
                      name: lightspeed-secrets
                env:
                  - name: MCP_HEADERS
                    value: '{"backstage-actions": {"Authorization": "Bearer backstage"}}'
                ports:
                  - containerPort: 8082
                    name: lightspeed-api
                    protocol: TCP
                readinessProbe:
                  tcpSocket:
                    port: 8082
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  timeoutSeconds: 5
                  successThreshold: 1
                  failureThreshold: 3
                startupProbe:
                  tcpSocket:
                    port: 8082
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  timeoutSeconds: 5
                  successThreshold: 1
                  failureThreshold: 20
                volumeMounts:
                  - mountPath: /app-root/lightspeed-stack.yaml
                    name: lightspeed-stack
                    subPath: lightspeed-stack.yaml
                  - mountPath: /tmp/data/feedback
                    name: shared-storage
                  - mountPath: /tmp/data/transcripts
                    name: shared-storage
                  - mountPath: /tmp/data/conversations
                    name: shared-storage
            volumes:
              - configMap:
                  name: lightspeed-stack
                name: lightspeed-stack
              - configMap:
                  name: llama-stack-config
                name: llama-stack-config
              - emptyDir: {}
                name: shared-storage
              - emptyDir: {}
                name: rag-data-volume
