apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
      mountPath: /opt/app-root/src # This mounts the Backstage config for Backstage itself
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    extraEnvs:
      secrets:
        - name: secrets-rhdh
        # - name: lightspeed-secrets  # Lightspeed plugin disabled (image version conflicts)
    extraFiles:
      configMaps:
        - name: rhdh-rbac-policy
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
  # Lightspeed/llama-stack sidecars disabled (image version conflicts: 0.2.17 vs 0.2.18, 0.4.4 tag missing)
  # deployment:
  #   patch:
  #     spec:
  #       template:
  #         spec:
  #           initContainers: ...
  #           containers: (llama-stack, lightspeed-core) ...
  #           volumes: ...
