kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-plugins-rhdh
  labels:
    rhdh.redhat.com/ext-config-sync: 'true'
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/backstage-community-plugin-rbac
        disabled: false
      - package:  ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-keycloak-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-gitlab-dynamic
        disabled: false
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-lightspeed:bs_1.39.1__0.5.7!red-hat-developer-hub-backstage-plugin-lightspeed
        disabled: false
        pluginConfig:
          lightspeed:
            # OPTIONAL: Custom users prompts displayed to users
            # If not provided, the plugin uses built-in default prompts
            prompts:
              - title: 'Getting Started with Red Hat Developer Hub'
                message: Can you guide me through the first steps to start using Developer Hub as a developer, like exploring the Software Catalog and adding my service?
          dynamicPlugins:
            frontend:
              red-hat-developer-hub.backstage-plugin-lightspeed:
                translationResources:
                  - importName: lightspeedTranslations
                    module: Alpha
                    ref: lightspeedTranslationRef
                appIcons:
                  - name: LightspeedIcon
                    module: LightspeedPlugin
                    importName: LightspeedIcon
                dynamicRoutes:
                  - path: /lightspeed
                    importName: LightspeedPage
                    module: LightspeedPlugin
                    menuItem:
                      icon: LightspeedIcon
                      text: Lightspeed
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-lightspeed-backend:bs_1.39.1__0.5.7!red-hat-developer-hub-backstage-plugin-lightspeed-backend
        disabled: false
        pluginConfig:
          lightspeed:
            # Connect to lightspeed-core service running as sidecar
            # lightspeed-core handles communication with LLM servers
            servers:
              - id: ${LLM_SERVER_ID}
                url: "http://localhost:8082"
                token: ""
    
            # Port for lightspeed-core service (running as sidecar)
            servicePort: 8082
            # OPTIONAL: Enable/disable question validation (default: true)
            # When enabled, restricts questions to RHDH-related topics for better security
            questionValidation: true
            
            # OPTIONAL: Custom user prompts displayed to users
            # If not provided, the plugin uses built-in default user prompts
            prompts:
              - title: "Quick Start"
                message: "How do I enable a dynamic plugin?"
            
            # OPTIONAL: Port for lightspeed service (default: 8080)
            # servicePort: 8080
            
            # OPTIONAL: Override default RHDH system prompt
            systemPrompt: "You are a helpful assistant focused on Red Hat Developer Hub development."            
      - package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic
        disabled: false
      # Kubernetes Backend Plugin
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-kubernetes-backend:bs_1.42.5__0.20.1!backstage-plugin-kubernetes-backend
        disabled: false
      # MCP server backend plugin (Latest version)
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-mcp-actions-backend:bs_1.42.5__0.1.2!backstage-plugin-mcp-actions-backend
        disabled: false
      # MCP tools plugins (Latest versions)
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-software-catalog-mcp-tool:next__0.4.0!red-hat-developer-hub-backstage-plugin-software-catalog-mcp-tool
        disabled: false
      # TechDocs MCP Tool - Temporarily disabled due to missing dependency @backstage/plugin-techdocs-node
      # - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/redhat-developer-hub-backstage-plugin-techdocs-mcp-tool:next__0.1.1!redhat-developer-hub-backstage-plugin-techdocs-mcp-tool
      #   disabled: false
      # Nexus Repository Manager Plugin (Frontend) - Latest version
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-nexus-repository-manager:next__1.16.0!backstage-community-plugin-nexus-repository-manager
        disabled: false
      # Tekton Plugin (Frontend) - Latest version
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-tekton:next__3.29.0!backstage-community-plugin-tekton
        disabled: false