apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy-dev-hub
  namespace: developer-hub
  labels:
    app: proxy-dev-hub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxy-dev-hub-anyuid-binding
  namespace: developer-hub
subjects:
  - kind: ServiceAccount
    name: proxy-dev-hub
    namespace: developer-hub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-mcp-proxy-config
  namespace: developer-hub
  labels:
    app: backstage-mcp-proxy
data:
  nginx.conf: |
    server {
        listen 8080;
        server_name _;
        
        # Logs para depuración
        access_log /dev/stdout;
        error_log /dev/stderr;

        # Proxy para /api/mcp-actions/v1 hacia Backstage
        # Maneja requests POST (STREAMABLE_HTTP) principalmente
        location ~ ^/api/mcp-actions/v1(/.*)?$ {
            proxy_pass http://developer-hub.developer-hub.svc.cluster.local:80$request_uri;
            proxy_http_version 1.1;
            
            # Headers estándar para Proxy
            proxy_set_header Host developer-hub.developer-hub.svc.cluster.local;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Header de autenticación para MCP (debe estar dentro del location)
            proxy_set_header Authorization "Bearer backstage";
            
            # Headers para requests POST (STREAMABLE_HTTP)
            # Forzar application/json para POST, preservar para otros métodos
            set $content_type_header $http_content_type;
            if ($request_method = POST) {
                set $content_type_header "application/json";
            }
            proxy_set_header Content-Type $content_type_header;
            
            # Configuración para streaming
            proxy_buffering off;
            proxy_read_timeout 24h;
            proxy_send_timeout 24h;
            proxy_set_header Cache-Control "no-cache";
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-mcp-proxy
  namespace: developer-hub
  labels:
    app: backstage-mcp-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-mcp-proxy
  template:
    metadata:
      labels:
        app: backstage-mcp-proxy
    spec:
      serviceAccountName: proxy-dev-hub
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:latest
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 101
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: backstage-mcp-proxy-config

---
apiVersion: v1
kind: Service
metadata:
  name: backstage-mcp-proxy
  namespace: developer-hub
  labels:
    app: backstage-mcp-proxy
spec:
  type: ClusterIP
  selector:
    app: backstage-mcp-proxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
