apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy-dev-hub
  namespace: developer-hub
  labels:
    app: proxy-dev-hub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxy-dev-hub-anyuid-binding
  namespace: developer-hub
subjects:
  - kind: ServiceAccount
    name: proxy-dev-hub
    namespace: developer-hub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-mcp-proxy-config
  namespace: developer-hub
  labels:
    app: backstage-mcp-proxy
data:
  nginx.conf: |
    server {
        listen 8080;
        server_name _;
        
        # Logs para depuración
        access_log /dev/stdout;
        error_log /dev/stderr;

        # Proxy para /api/mcp-actions/v1 hacia Backstage
        # Maneja tanto requests normales como SSE (Server-Sent Events)
        location / {
            proxy_pass http://backstage-developer-hub:80/api/mcp-actions/v1;
            proxy_http_version 1.1;
            
            # Headers estándar para Proxy
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Header de autenticación para MCP (debe estar dentro del location)
            proxy_set_header Authorization "Bearer backstage";
            
            # Headers para SSE (Server-Sent Events) - GET requests
            proxy_set_header Cache-Control "no-cache";
            proxy_buffering off;
            proxy_read_timeout 24h;
            proxy_send_timeout 24h;
            
            # Preservar content-type solo si está presente (no forzar para GET/SSE)
            # Si no hay content-type en la request, no lo agregamos (para GET requests)
            proxy_set_header Content-Type $http_content_type;
            
            # Asegurar que los métodos HTTP se preserven correctamente
            # Nginx preserva automáticamente el método HTTP, pero necesitamos asegurar
            # que POST requests tengan el content-type correcto
            if ($request_method = POST) {
                proxy_set_header Content-Type "application/json";
            }
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-mcp-proxy
  namespace: developer-hub
  labels:
    app: backstage-mcp-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-mcp-proxy
  template:
    metadata:
      labels:
        app: backstage-mcp-proxy
    spec:
      serviceAccountName: proxy-dev-hub
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:latest
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 101
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: backstage-mcp-proxy-config

---
apiVersion: v1
kind: Service
metadata:
  name: backstage-mcp-proxy
  namespace: developer-hub
  labels:
    app: backstage-mcp-proxy
spec:
  type: ClusterIP
  selector:
    app: backstage-mcp-proxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
