kind: ConfigMap
apiVersion: v1
metadata:
  name: rhdh-rbac-policy
  labels:
    rhdh.redhat.com/ext-config-sync: 'true'
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  rbac-policy.csv: |
    # ==========================================================
    # 1. BASE PERMISSIONS FOR ALL AUTHENTICATED USERS
    # ==========================================================
    # The 'role:default/authenticated' role is automatically assigned to any logged-in user.
    # These permissions apply to ALL users
    
    # Lightspeed permissions for ALL users
    p, role:default/authenticated, lightspeed.chat, read, allow
    p, role:default/authenticated, lightspeed.chat, create, allow
    p, role:default/authenticated, lightspeed.chat, update, allow
    p, role:default/authenticated, lightspeed.chat, delete, allow
    
    # Catalog permissions for ALL users
    p, role:default/authenticated, catalog-entity, read, allow
    p, role:default/authenticated, catalog.location, read, allow
    
    # Scaffolder permissions for ALL users
    p, role:default/authenticated, scaffolder-template, read, allow
    p, role:default/authenticated, scaffolder.task, read, allow
    p, role:default/authenticated, scaffolder.task, create, allow
    p, role:default/authenticated, scaffolder.action.execute, use, allow

    # ==========================================================
    # 2. PLATFORM ENGINEER ROLE (Full Admin Permissions)
    # ==========================================================
    # Define a comprehensive 'admin' role
    p, role:default/platformengineer, lightspeed.chat, read, allow
    p, role:default/platformengineer, lightspeed.chat, create, allow
    p, role:default/platformengineer, lightspeed.chat, update, allow
    p, role:default/platformengineer, lightspeed.chat, delete, allow

    p, role:default/platformengineer, catalog-entity, read, allow
    p, role:default/platformengineer, catalog-entity, create, allow
    p, role:default/platformengineer, catalog-entity, update, allow
    p, role:default/platformengineer, catalog-entity, delete, allow

    p, role:default/platformengineer, catalog.location, read, allow
    p, role:default/platformengineer, catalog.location, create, allow
    p, role:default/platformengineer, catalog.location, delete, allow

    p, role:default/platformengineer, catalog.entity.create, create, allow
    p, role:default/platformengineer, scaffolder-template, read, allow
    p, role:default/platformengineer, scaffolder.task, read, allow
    p, role:default/platformengineer, scaffolder.task, create, allow
    p, role:default/platformengineer, scaffolder.task, delete, allow
    p, role:default/platformengineer, scaffolder.action.execute, use, allow

    p, role:default/platformengineer, permission.policy, read, allow

    # ==========================================================
    # 3. DIRECT USER PERMISSIONS (Applied First)
    # ==========================================================
    # Direct Lightspeed permissions for all users (fallback)
    # This ensures permissions work even if role resolution has issues
    # These are applied BEFORE role assignments
    
    # Platform Engineers - Direct permissions
    p, user:default/maximilianopizarro, lightspeed.chat, read, allow
    p, user:default/maximilianopizarro, lightspeed.chat, create, allow
    p, user:default/maximilianopizarro, lightspeed.chat, update, allow
    p, user:default/maximilianopizarro, lightspeed.chat, delete, allow
    p, user:default/user5-infra, lightspeed.chat, read, allow
    p, user:default/user5-infra, lightspeed.chat, create, allow
    p, user:default/user5-infra, lightspeed.chat, update, allow
    p, user:default/user5-infra, lightspeed.chat, delete, allow
    p, user:default/user6-infra, lightspeed.chat, read, allow
    p, user:default/user6-infra, lightspeed.chat, create, allow
    p, user:default/user6-infra, lightspeed.chat, update, allow
    p, user:default/user6-infra, lightspeed.chat, delete, allow
    p, user:default/user7-platform, lightspeed.chat, read, allow
    p, user:default/user7-platform, lightspeed.chat, create, allow
    p, user:default/user7-platform, lightspeed.chat, update, allow
    p, user:default/user7-platform, lightspeed.chat, delete, allow
    p, user:default/user8-platform, lightspeed.chat, read, allow
    p, user:default/user8-platform, lightspeed.chat, create, allow
    p, user:default/user8-platform, lightspeed.chat, update, allow
    p, user:default/user8-platform, lightspeed.chat, delete, allow
    p, user:default/user9-rhdh, lightspeed.chat, read, allow
    p, user:default/user9-rhdh, lightspeed.chat, create, allow
    p, user:default/user9-rhdh, lightspeed.chat, update, allow
    p, user:default/user9-rhdh, lightspeed.chat, delete, allow
    p, user:default/user10-rhdh, lightspeed.chat, read, allow
    p, user:default/user10-rhdh, lightspeed.chat, create, allow
    p, user:default/user10-rhdh, lightspeed.chat, update, allow
    p, user:default/user10-rhdh, lightspeed.chat, delete, allow
    
    # Developers - Direct permissions
    p, user:default/user1-dev, lightspeed.chat, read, allow
    p, user:default/user1-dev, lightspeed.chat, create, allow
    p, user:default/user1-dev, lightspeed.chat, update, allow
    p, user:default/user1-dev, lightspeed.chat, delete, allow
    p, user:default/user2-dev, lightspeed.chat, read, allow
    p, user:default/user2-dev, lightspeed.chat, create, allow
    p, user:default/user2-dev, lightspeed.chat, update, allow
    p, user:default/user2-dev, lightspeed.chat, delete, allow
    
    # Dev Team 1 - Direct permissions
    p, user:default/user3-devteam1, lightspeed.chat, read, allow
    p, user:default/user3-devteam1, lightspeed.chat, create, allow
    p, user:default/user3-devteam1, lightspeed.chat, update, allow
    p, user:default/user3-devteam1, lightspeed.chat, delete, allow
    p, user:default/user4-devteam1, lightspeed.chat, read, allow
    p, user:default/user4-devteam1, lightspeed.chat, create, allow
    p, user:default/user4-devteam1, lightspeed.chat, update, allow
    p, user:default/user4-devteam1, lightspeed.chat, delete, allow

    # ==========================================================
    # 4. USER ROLE ASSIGNMENTS
    # ==========================================================
    # Assign users to roles based on their groups
    # These are applied AFTER direct permissions
    
    # Platform Engineers (Full Admin Permissions)
    # Users in infrastructure, platformengineers, and rhdh groups get admin role
    g, user:default/maximilianopizarro, role:default/platformengineer
    g, user:default/user5-infra, role:default/platformengineer
    g, user:default/user6-infra, role:default/platformengineer
    g, user:default/user7-platform, role:default/platformengineer
    g, user:default/user8-platform, role:default/platformengineer
    g, user:default/user9-rhdh, role:default/platformengineer
    g, user:default/user10-rhdh, role:default/platformengineer
    
    # Developers (Basic Users - inherit from authenticated role)
    # user1-dev and user2-dev inherit permissions from role:default/authenticated
    # They already have full Lightspeed permissions through authenticated role
    g, user:default/user1-dev, role:default/authenticated
    g, user:default/user2-dev, role:default/authenticated
    
    # Dev Team 1 (Basic Users - inherit from authenticated role)
    # user3-devteam1 and user4-devteam1 inherit permissions from role:default/authenticated
    # They already have full Lightspeed permissions through authenticated role
    g, user:default/user3-devteam1, role:default/authenticated
    g, user:default/user4-devteam1, role:default/authenticated

    # ==========================================================
    # 5. LEGACY ROLES (Optional - for backward compatibility)
    # ==========================================================
    # If you still want the 'rhdhpai-users' role for other users, keep its definition:
    p, role:default/rhdhpai-users, lightspeed.chat.read, read, allow
    p, role:default/rhdhpai-users, lightspeed.chat.create, create, allow
    p, role:default/rhdhpai-users, lightspeed.chat.delete, delete, allow    
    p, role:default/rhdhpai-users, catalog-entity, read, allow
    p, role:default/rhdhpai-users, catalog-entity, update, allow
    p, role:default/rhdhpai-users, catalog-entity, delete, allow
    p, role:default/rhdhpai-users, catalog.location.read, read, allow
    p, role:default/rhdhpai-users, catalog.location.create, create, allow
    p, role:default/rhdhpai-users, catalog.location.delete, delete, allow
    p, role:default/rhdhpai-users, catalog.entity.create, create, allow
    p, role:default/rhdhpai-users, scaffolder-template, read, allow
    p, role:default/rhdhpai-users, scaffolder.task.read, read, allow
    p, role:default/rhdhpai-users, scaffolder.task.create, create, allow

    # If you still need 'template-executers' for other users, keep its definition:
    p, role:default/template-executers, scaffolder.action.execute, use, allow

    g, user:default/maximilianopizarro, role:default/rhdhpai-users
    g, user:default/maximilianopizarro, role:default/template-executers