kind: ConfigMap
apiVersion: v1
metadata:
  name: rhdh-rbac-policy
  labels:
    rhdh.redhat.com/ext-config-sync: 'true'
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  rbac-policy.csv: |
    # ==========================================================
    # 1. PERMISOS BASE PARA TODOS (Soluciona el error de Lightspeed)
    # ==========================================================
    # El rol 'role:default/authenticated' se asigna automáticamente a cualquier usuario logueado.
    
    # Permitir a TODOS usar Lightspeed (Chat AI)
    p, role:default/authenticated, lightspeed.chat, read, allow
    p, role:default/authenticated, lightspeed.chat, create, allow
    
    # Permitir a TODOS ver el catálogo y documentación básica
    p, role:default/authenticated, catalog-entity, read, allow
    p, role:default/authenticated, catalog.location, read, allow
    p, role:default/authenticated, techdocs.entity, read, allow
    
    # Permitir a TODOS ejecutar templates (Scaffolder)
    p, role:default/authenticated, scaffolder-template, read, allow
    p, role:default/authenticated, scaffolder.action.execute, use, allow
    p, role:default/authenticated, scaffolder.task, read, allow
    p, role:default/authenticated, scaffolder.task, create, allow

    # ==========================================================
    # 2. DEFINICIÓN DEL ROL ADMIN (Platform Engineers)
    # ==========================================================
    # Este rol tiene control total (CRUD) sobre todo el sistema
    
    # Control total sobre Lightspeed (incluye borrar conversaciones)
    p, role:default/platform-admin, lightspeed.chat, update, allow
    p, role:default/platform-admin, lightspeed.chat, delete, allow
    
    # Control total del Catálogo
    p, role:default/platform-admin, catalog-entity, create, allow
    p, role:default/platform-admin, catalog-entity, update, allow
    p, role:default/platform-admin, catalog-entity, delete, allow
    p, role:default/platform-admin, catalog.location, create, allow
    p, role:default/platform-admin, catalog.location, delete, allow
    p, role:default/platform-admin, catalog.entity.create, create, allow
    
    # Control total de Templates y Tareas
    p, role:default/platform-admin, scaffolder-template, write, allow
    p, role:default/platform-admin, scaffolder.task, delete, allow
    
    # Gestión de Permisos y Políticas (Muy importante para admins)
    p, role:default/platform-admin, permission.policy, read, allow
    p, role:default/platform-admin, permission.policy, create, allow
    p, role:default/platform-admin, permission.policy, update, allow
    p, role:default/platform-admin, permission.policy, delete, allow

    # Gestión de Plugins Dinámicos
    p, role:default/platform-admin, plugin.dynamic, read, allow
    p, role:default/platform-admin, plugin.dynamic, create, allow
    p, role:default/platform-admin, plugin.dynamic, update, allow
    p, role:default/platform-admin, plugin.dynamic, delete, allow
    p, role:default/platform-admin, plugin.dynamic, install, allow
    p, role:default/platform-admin, plugin.dynamic, uninstall, allow

    # ==========================================================
    # 3. ASIGNACIÓN DE GRUPOS Y USUARIOS A ROLES
    # ==========================================================
    
    # Asignar tu usuario al rol de Admin
    g, user:default/maximilianopizarro, role:default/platform-admin
    
    # Asignar grupos técnicos al rol de Admin (si vienen de Keycloak u otro proveedor)
    g, group:default/platform-team, role:default/platform-admin
    g, group:default/infrastructure, role:default/platform-admin
    g, group:default/rhdh, role:default/platform-admin

    # NOTA: Los usuarios normales (developers) no necesitan asignación explícita
    # porque ya heredan los permisos de la sección 1 (role:default/authenticated).