kind: ConfigMap
apiVersion: v1
metadata:
  name: rhdh-rbac-policy
  labels:
    rhdh.redhat.com/ext-config-sync: 'true'
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  rbac-policy.csv: |
    # ============================================
    # FULL ADMIN PERMISSIONS FOR maximilianopizarro
    # ============================================
    
    # Note: user9-rhdh admin permissions are defined below
    
    # Catalog Entity Permissions - Full CRUD
    p, user:default/maximilianopizarro, catalog-entity, read, allow
    p, user:default/maximilianopizarro, catalog-entity, create, allow
    p, user:default/maximilianopizarro, catalog-entity, update, allow
    p, user:default/maximilianopizarro, catalog-entity, delete, allow
    
    # Catalog Location Permissions - Full CRUD
    p, user:default/maximilianopizarro, catalog.location, read, allow
    p, user:default/maximilianopizarro, catalog.location, create, allow
    p, user:default/maximilianopizarro, catalog.location, update, allow
    p, user:default/maximilianopizarro, catalog.location, delete, allow
    
    # Catalog Entity Creation Permission
    p, user:default/maximilianopizarro, catalog.entity.create, create, allow
    
    # Permission Policy Management - Full CRUD
    p, user:default/maximilianopizarro, permission.policy, read, allow
    p, user:default/maximilianopizarro, permission.policy, create, allow
    p, user:default/maximilianopizarro, permission.policy, update, allow
    p, user:default/maximilianopizarro, permission.policy, delete, allow
    
    # Scaffolder Permissions - Full Access
    p, user:default/maximilianopizarro, scaffolder-template, read, allow
    p, user:default/maximilianopizarro, scaffolder-template, write, allow
    p, user:default/maximilianopizarro, scaffolder.task, read, allow
    p, user:default/maximilianopizarro, scaffolder.task, create, allow
    p, user:default/maximilianopizarro, scaffolder.task, update, allow
    p, user:default/maximilianopizarro, scaffolder.task, delete, allow
    p, user:default/maximilianopizarro, scaffolder.action.execute, use, allow
    
    # Lightspeed (AI Chat) Permissions - Full CRUD
    p, user:default/maximilianopizarro, lightspeed.chat, read, allow
    p, user:default/maximilianopizarro, lightspeed.chat, create, allow
    p, user:default/maximilianopizarro, lightspeed.chat, update, allow
    p, user:default/maximilianopizarro, lightspeed.chat, delete, allow
    
    # TechDocs Permissions - Full Access
    p, user:default/maximilianopizarro, techdocs.entity, read, allow
    p, user:default/maximilianopizarro, techdocs.entity, create, allow
    p, user:default/maximilianopizarro, techdocs.entity, update, allow
    p, user:default/maximilianopizarro, techdocs.entity, delete, allow
    
    # API Permissions - Full Access
    p, user:default/maximilianopizarro, api.entity, read, allow
    p, user:default/maximilianopizarro, api.entity, create, allow
    p, user:default/maximilianopizarro, api.entity, update, allow
    p, user:default/maximilianopizarro, api.entity, delete, allow
    
    # Resource Permissions - Full Access
    p, user:default/maximilianopizarro, resource.entity, read, allow
    p, user:default/maximilianopizarro, resource.entity, create, allow
    p, user:default/maximilianopizarro, resource.entity, update, allow
    p, user:default/maximilianopizarro, resource.entity, delete, allow
    
    # System Permissions - Full Access
    p, user:default/maximilianopizarro, system.entity, read, allow
    p, user:default/maximilianopizarro, system.entity, create, allow
    p, user:default/maximilianopizarro, system.entity, update, allow
    p, user:default/maximilianopizarro, system.entity, delete, allow
    
    # Domain Permissions - Full Access
    p, user:default/maximilianopizarro, domain.entity, read, allow
    p, user:default/maximilianopizarro, domain.entity, create, allow
    p, user:default/maximilianopizarro, domain.entity, update, allow
    p, user:default/maximilianopizarro, domain.entity, delete, allow
    
    # Group Permissions - Full Access
    p, user:default/maximilianopizarro, group.entity, read, allow
    p, user:default/maximilianopizarro, group.entity, create, allow
    p, user:default/maximilianopizarro, group.entity, update, allow
    p, user:default/maximilianopizarro, group.entity, delete, allow
    
    # User Permissions - Full Access
    p, user:default/maximilianopizarro, user.entity, read, allow
    p, user:default/maximilianopizarro, user.entity, create, allow
    p, user:default/maximilianopizarro, user.entity, update, allow
    p, user:default/maximilianopizarro, user.entity, delete, allow
    
    # Template Permissions - Full Access
    p, user:default/maximilianopizarro, template.entity, read, allow
    p, user:default/maximilianopizarro, template.entity, create, allow
    p, user:default/maximilianopizarro, template.entity, update, allow
    p, user:default/maximilianopizarro, template.entity, delete, allow
    
    # Dynamic Plugins Permissions - Full Access (Install, View, Configure)
    p, user:default/maximilianopizarro, plugin.dynamic, read, allow
    p, user:default/maximilianopizarro, plugin.dynamic, create, allow
    p, user:default/maximilianopizarro, plugin.dynamic, update, allow
    p, user:default/maximilianopizarro, plugin.dynamic, delete, allow
    p, user:default/maximilianopizarro, plugin.dynamic, install, allow
    p, user:default/maximilianopizarro, plugin.dynamic, uninstall, allow
    
    # Plugin Configuration Permissions - Full Access
    p, user:default/maximilianopizarro, plugin.config, read, allow
    p, user:default/maximilianopizarro, plugin.config, create, allow
    p, user:default/maximilianopizarro, plugin.config, update, allow
    p, user:default/maximilianopizarro, plugin.config, delete, allow
    
    # ============================================
    # ROLE DEFINITIONS FOR OTHER USERS (Optional)
    # ============================================
    
    # Define a comprehensive 'platformengineer' role
    p, role:default/platformengineer, lightspeed.chat, read, allow
    p, role:default/platformengineer, lightspeed.chat, create, allow
    p, role:default/platformengineer, lightspeed.chat, update, allow
    p, role:default/platformengineer, lightspeed.chat, delete, allow
    p, role:default/platformengineer, catalog-entity, read, allow
    p, role:default/platformengineer, catalog-entity, create, allow
    p, role:default/platformengineer, catalog-entity, update, allow
    p, role:default/platformengineer, catalog-entity, delete, allow
    p, role:default/platformengineer, catalog.location, read, allow
    p, role:default/platformengineer, catalog.location, create, allow
    p, role:default/platformengineer, catalog.location, delete, allow
    p, role:default/platformengineer, catalog.entity.create, create, allow
    p, role:default/platformengineer, scaffolder-template, read, allow
    p, role:default/platformengineer, scaffolder.task, read, allow
    p, role:default/platformengineer, scaffolder.task, create, allow
    p, role:default/platformengineer, scaffolder.task, delete, allow
    p, role:default/platformengineer, scaffolder.action.execute, use, allow
    p, role:default/platformengineer, permission.policy, read, allow
    p, role:default/platformengineer, plugin.dynamic, read, allow
    p, role:default/platformengineer, plugin.dynamic, install, allow
    p, role:default/platformengineer, plugin.config, read, allow
    
    # Assign maximilianopizarro to platformengineer role (additional role assignment)
    g, user:default/maximilianopizarro, role:default/platformengineer
    
    # If you still want the 'rhdhpai-users' role for other users, keep its definition:
    p, role:default/rhdhpai-users, lightspeed.chat.read, read, allow
    p, role:default/rhdhpai-users, lightspeed.chat.create, create, allow
    p, role:default/rhdhpai-users, lightspeed.chat.delete, delete, allow    
    p, role:default/rhdhpai-users, catalog-entity, read, allow
    p, role:default/rhdhpai-users, catalog-entity, update, allow
    p, role:default/rhdhpai-users, catalog-entity, delete, allow
    p, role:default/rhdhpai-users, catalog.location.read, read, allow
    p, role:default/rhdhpai-users, catalog.location.create, create, allow
    p, role:default/rhdhpai-users, catalog.location.delete, delete, allow
    p, role:default/rhdhpai-users, catalog.entity.create, create, allow
    p, role:default/rhdhpai-users, scaffolder-template, read, allow
    p, role:default/rhdhpai-users, scaffolder.task.read, read, allow
    p, role:default/rhdhpai-users, scaffolder.task.create, create, allow
    
    # If you still need 'template-executers' for other users, keep its definition:
    p, role:default/template-executers, scaffolder.action.execute, use, allow
    
    # Additional role assignments for maximilianopizarro (redundant but ensures coverage)
    g, user:default/maximilianopizarro, role:default/rhdhpai-users
    g, user:default/maximilianopizarro, role:default/template-executers
    
    # ============================================
    # FULL ADMIN PERMISSIONS FOR user9-rhdh
    # ============================================
    
    # Catalog Entity Permissions - Full CRUD
    p, user:default/user9-rhdh, catalog-entity, read, allow
    p, user:default/user9-rhdh, catalog-entity, create, allow
    p, user:default/user9-rhdh, catalog-entity, update, allow
    p, user:default/user9-rhdh, catalog-entity, delete, allow
    
    # Catalog Location Permissions - Full CRUD
    p, user:default/user9-rhdh, catalog.location, read, allow
    p, user:default/user9-rhdh, catalog.location, create, allow
    p, user:default/user9-rhdh, catalog.location, update, allow
    p, user:default/user9-rhdh, catalog.location, delete, allow
    
    # Catalog Entity Creation Permission
    p, user:default/user9-rhdh, catalog.entity.create, create, allow
    
    # Permission Policy Management - Full CRUD
    p, user:default/user9-rhdh, permission.policy, read, allow
    p, user:default/user9-rhdh, permission.policy, create, allow
    p, user:default/user9-rhdh, permission.policy, update, allow
    p, user:default/user9-rhdh, permission.policy, delete, allow
    
    # Scaffolder Permissions - Full Access
    p, user:default/user9-rhdh, scaffolder-template, read, allow
    p, user:default/user9-rhdh, scaffolder-template, write, allow
    p, user:default/user9-rhdh, scaffolder.task, read, allow
    p, user:default/user9-rhdh, scaffolder.task, create, allow
    p, user:default/user9-rhdh, scaffolder.task, update, allow
    p, user:default/user9-rhdh, scaffolder.task, delete, allow
    p, user:default/user9-rhdh, scaffolder.action.execute, use, allow
    
    # Lightspeed (AI Chat) Permissions - Full CRUD
    p, user:default/user9-rhdh, lightspeed.chat, read, allow
    p, user:default/user9-rhdh, lightspeed.chat, create, allow
    p, user:default/user9-rhdh, lightspeed.chat, update, allow
    p, user:default/user9-rhdh, lightspeed.chat, delete, allow
    
    # TechDocs Permissions - Full Access
    p, user:default/user9-rhdh, techdocs.entity, read, allow
    p, user:default/user9-rhdh, techdocs.entity, create, allow
    p, user:default/user9-rhdh, techdocs.entity, update, allow
    p, user:default/user9-rhdh, techdocs.entity, delete, allow
    
    # API Permissions - Full Access
    p, user:default/user9-rhdh, api.entity, read, allow
    p, user:default/user9-rhdh, api.entity, create, allow
    p, user:default/user9-rhdh, api.entity, update, allow
    p, user:default/user9-rhdh, api.entity, delete, allow
    
    # Resource Permissions - Full Access
    p, user:default/user9-rhdh, resource.entity, read, allow
    p, user:default/user9-rhdh, resource.entity, create, allow
    p, user:default/user9-rhdh, resource.entity, update, allow
    p, user:default/user9-rhdh, resource.entity, delete, allow
    
    # System Permissions - Full Access
    p, user:default/user9-rhdh, system.entity, read, allow
    p, user:default/user9-rhdh, system.entity, create, allow
    p, user:default/user9-rhdh, system.entity, update, allow
    p, user:default/user9-rhdh, system.entity, delete, allow
    
    # Domain Permissions - Full Access
    p, user:default/user9-rhdh, domain.entity, read, allow
    p, user:default/user9-rhdh, domain.entity, create, allow
    p, user:default/user9-rhdh, domain.entity, update, allow
    p, user:default/user9-rhdh, domain.entity, delete, allow
    
    # Group Permissions - Full Access
    p, user:default/user9-rhdh, group.entity, read, allow
    p, user:default/user9-rhdh, group.entity, create, allow
    p, user:default/user9-rhdh, group.entity, update, allow
    p, user:default/user9-rhdh, group.entity, delete, allow
    
    # User Permissions - Full Access
    p, user:default/user9-rhdh, user.entity, read, allow
    p, user:default/user9-rhdh, user.entity, create, allow
    p, user:default/user9-rhdh, user.entity, update, allow
    p, user:default/user9-rhdh, user.entity, delete, allow
    
    # Template Permissions - Full Access
    p, user:default/user9-rhdh, template.entity, read, allow
    p, user:default/user9-rhdh, template.entity, create, allow
    p, user:default/user9-rhdh, template.entity, update, allow
    p, user:default/user9-rhdh, template.entity, delete, allow
    
    # Dynamic Plugins Permissions - Full Access (Install, View, Configure)
    p, user:default/user9-rhdh, plugin.dynamic, read, allow
    p, user:default/user9-rhdh, plugin.dynamic, create, allow
    p, user:default/user9-rhdh, plugin.dynamic, update, allow
    p, user:default/user9-rhdh, plugin.dynamic, delete, allow
    p, user:default/user9-rhdh, plugin.dynamic, install, allow
    p, user:default/user9-rhdh, plugin.dynamic, uninstall, allow
    
    # Plugin Configuration Permissions - Full Access
    p, user:default/user9-rhdh, plugin.config, read, allow
    p, user:default/user9-rhdh, plugin.config, create, allow
    p, user:default/user9-rhdh, plugin.config, update, allow
    p, user:default/user9-rhdh, plugin.config, delete, allow
    
    # Assign user9-rhdh to platformengineer role
    g, user:default/user9-rhdh, role:default/platformengineer
    g, user:default/user9-rhdh, role:default/rhdhpai-users
    g, user:default/user9-rhdh, role:default/template-executers
    
    # ============================================
    # BASIC PERMISSIONS FOR ALL AUTHENTICATED USERS
    # ============================================
    # These permissions allow any authenticated user to:
    # - Sign in and access the application
    # - View catalog entities (read-only)
    # - View catalog locations (read-only)
    # - View TechDocs
    # - View APIs
    # - View Resources
    # - View Systems
    # - View Domains
    # - View Groups
    # - View Users (their own profile)
    
    # Catalog Entity Permissions - Read Only
    p, role:default/authenticated, catalog-entity, read, allow
    
    # Catalog Location Permissions - Read Only
    p, role:default/authenticated, catalog.location, read, allow
    
    # TechDocs Permissions - Read Only
    p, role:default/authenticated, techdocs.entity, read, allow
    
    # API Permissions - Read Only
    p, role:default/authenticated, api.entity, read, allow
    
    # Resource Permissions - Read Only
    p, role:default/authenticated, resource.entity, read, allow
    
    # System Permissions - Read Only
    p, role:default/authenticated, system.entity, read, allow
    
    # Domain Permissions - Read Only
    p, role:default/authenticated, domain.entity, read, allow
    
    # Group Permissions - Read Only
    p, role:default/authenticated, group.entity, read, allow
    
    # User Permissions - Read Only (users can view their own profile)
    p, role:default/authenticated, user.entity, read, allow
    
    # Scaffolder Template Permissions - Read Only (users can view templates)
    p, role:default/authenticated, scaffolder-template, read, allow
    
    # Assign all authenticated users to the authenticated role
    # This is automatically done by Backstage for logged-in users
