kind: ConfigMap
apiVersion: v1
metadata:
  name: rhdh-rbac-policy
  labels:
    rhdh.redhat.com/ext-config-sync: 'true'
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  rbac-policy.csv: |
    # ==========================================================
    # 1. BASE PERMISSIONS FOR ALL USERS (Fixes Lightspeed error)
    # ==========================================================
    # The 'role:default/authenticated' role is automatically assigned to any logged-in user.
    
    # Allow ALL users to use Lightspeed (AI Chat)
    p, role:default/authenticated, lightspeed.chat, read, allow
    p, role:default/authenticated, lightspeed.chat, create, allow
    # Allow ALL users to list available models
    p, role:default/authenticated, lightspeed.models, read, allow
    
    # Allow ALL users to view catalog and basic documentation
    p, role:default/authenticated, catalog-entity, read, allow
    p, role:default/authenticated, catalog.location, read, allow
    p, role:default/authenticated, techdocs.entity, read, allow
    
    # Allow ALL users to execute templates (Scaffolder)
    p, role:default/authenticated, scaffolder-template, read, allow
    p, role:default/authenticated, scaffolder.action.execute, use, allow
    p, role:default/authenticated, scaffolder.task, read, allow
    p, role:default/authenticated, scaffolder.task, create, allow

    # ==========================================================
    # 2. TEAM ROLES WITH FULL LIGHTSPEED PERMISSIONS
    # ==========================================================
    # Each team gets a role with full Lightspeed permissions (read, create, update, delete)
    
    # Developers Team Role
    p, role:default/developers, lightspeed.chat, read, allow
    p, role:default/developers, lightspeed.chat, create, allow
    p, role:default/developers, lightspeed.chat, update, allow
    p, role:default/developers, lightspeed.chat, delete, allow
    p, role:default/developers, lightspeed.models, read, allow
    
    # Dev Team 1 Role
    p, role:default/devteam1, lightspeed.chat, read, allow
    p, role:default/devteam1, lightspeed.chat, create, allow
    p, role:default/devteam1, lightspeed.chat, update, allow
    p, role:default/devteam1, lightspeed.chat, delete, allow
    p, role:default/devteam1, lightspeed.models, read, allow
    
    # Infrastructure Team Role
    p, role:default/infrastructure, lightspeed.chat, read, allow
    p, role:default/infrastructure, lightspeed.chat, create, allow
    p, role:default/infrastructure, lightspeed.chat, update, allow
    p, role:default/infrastructure, lightspeed.chat, delete, allow
    p, role:default/infrastructure, lightspeed.models, read, allow
    
    # Platform Engineers Team Role
    p, role:default/platformengineers, lightspeed.chat, read, allow
    p, role:default/platformengineers, lightspeed.chat, create, allow
    p, role:default/platformengineers, lightspeed.chat, update, allow
    p, role:default/platformengineers, lightspeed.chat, delete, allow
    p, role:default/platformengineers, lightspeed.models, read, allow
    
    # RHDH Team Role
    p, role:default/rhdh, lightspeed.chat, read, allow
    p, role:default/rhdh, lightspeed.chat, create, allow
    p, role:default/rhdh, lightspeed.chat, update, allow
    p, role:default/rhdh, lightspeed.chat, delete, allow
    p, role:default/rhdh, lightspeed.models, read, allow
    
    # Platform Team Role (Legacy)
    p, role:default/platform-team, lightspeed.chat, read, allow
    p, role:default/platform-team, lightspeed.chat, create, allow
    p, role:default/platform-team, lightspeed.chat, update, allow
    p, role:default/platform-team, lightspeed.chat, delete, allow
    p, role:default/platform-team, lightspeed.models, read, allow
    
    # Application Team Role (Legacy)
    p, role:default/application-team, lightspeed.chat, read, allow
    p, role:default/application-team, lightspeed.chat, create, allow
    p, role:default/application-team, lightspeed.chat, update, allow
    p, role:default/application-team, lightspeed.chat, delete, allow
    p, role:default/application-team, lightspeed.models, read, allow
    
    # Janus Authors Team Role
    p, role:default/janus-authors, lightspeed.chat, read, allow
    p, role:default/janus-authors, lightspeed.chat, create, allow
    p, role:default/janus-authors, lightspeed.chat, update, allow
    p, role:default/janus-authors, lightspeed.chat, delete, allow
    p, role:default/janus-authors, lightspeed.models, read, allow

    # ==========================================================
    # 3. ADMIN ROLE DEFINITION (Platform Engineers)
    # ==========================================================
    # This role has full control (CRUD) over the entire system
    
    # Full control over Lightspeed (already covered by team role, but kept for clarity)
    p, role:default/platform-admin, lightspeed.chat, read, allow
    p, role:default/platform-admin, lightspeed.chat, create, allow
    p, role:default/platform-admin, lightspeed.chat, update, allow
    p, role:default/platform-admin, lightspeed.chat, delete, allow
    p, role:default/platform-admin, lightspeed.models, read, allow
    
    # Full control over Catalog
    p, role:default/platform-admin, catalog-entity, create, allow
    p, role:default/platform-admin, catalog-entity, update, allow
    p, role:default/platform-admin, catalog-entity, delete, allow
    p, role:default/platform-admin, catalog.location, create, allow
    p, role:default/platform-admin, catalog.location, delete, allow
    p, role:default/platform-admin, catalog.entity.create, create, allow
    
    # Full control over Templates and Tasks
    p, role:default/platform-admin, scaffolder-template, write, allow
    p, role:default/platform-admin, scaffolder.task, delete, allow
    
    # Permission and Policy Management (Very important for admins)
    p, role:default/platform-admin, permission.policy, read, allow
    p, role:default/platform-admin, permission.policy, create, allow
    p, role:default/platform-admin, permission.policy, update, allow
    p, role:default/platform-admin, permission.policy, delete, allow

    # Dynamic Plugins Management
    p, role:default/platform-admin, plugin.dynamic, read, allow
    p, role:default/platform-admin, plugin.dynamic, create, allow
    p, role:default/platform-admin, plugin.dynamic, update, allow
    p, role:default/platform-admin, plugin.dynamic, delete, allow
    p, role:default/platform-admin, plugin.dynamic, install, allow
    p, role:default/platform-admin, plugin.dynamic, uninstall, allow

    # ==========================================================
    # 4. GROUP AND USER ROLE ASSIGNMENTS
    # ==========================================================
    # Groups must match EXACTLY with the names in Keycloak
    # Keycloak groups: developers, devteam1, infrastructure, platformengineers, rhdh
    
    # Assign groups to their team roles (full Lightspeed permissions)
    g, group:default/developers, role:default/developers
    g, group:default/devteam1, role:default/devteam1
    g, group:default/infrastructure, role:default/infrastructure
    g, group:default/platformengineers, role:default/platformengineers
    g, group:default/rhdh, role:default/rhdh
    g, group:default/platform-team, role:default/platform-team
    g, group:default/application-team, role:default/application-team
    g, group:default/janus-authors, role:default/janus-authors
    
    # Assign your user to Admin role and team roles
    g, user:default/maximilianopizarro, role:default/platform-admin
    g, user:default/maximilianopizarro, role:default/platformengineers
    g, user:default/maximilianopizarro, role:default/platform-team
    g, user:default/maximilianopizarro, role:default/rhdh
    
    # Assign Keycloak technical groups to Admin role (for full system control)
    # These groups also have team roles above for Lightspeed permissions
    g, group:default/platformengineers, role:default/platform-admin
    g, group:default/infrastructure, role:default/platform-admin
    g, group:default/rhdh, role:default/platform-admin
    g, group:default/platform-team, role:default/platform-admin

    # NOTE: All users now have full Lightspeed permissions through their team roles
    # Platform teams also have full system control through platform-admin role