kind: ConfigMap
apiVersion: v1
metadata:
  name: rhdh-rbac-policy
  labels:
    rhdh.redhat.com/ext-config-sync: 'true'
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  rbac-policy.csv: |
    # ==========================================================
    # 1. BASE PERMISSIONS FOR ALL USERS (Fixes Lightspeed error)
    # ==========================================================
    # The 'role:default/authenticated' role is automatically assigned to any logged-in user.
    
    # Allow ALL users to use Lightspeed (AI Chat)
    p, role:default/authenticated, lightspeed.chat, read, allow
    p, role:default/authenticated, lightspeed.chat, create, allow
    
    # Allow ALL users to view catalog and basic documentation
    p, role:default/authenticated, catalog-entity, read, allow
    p, role:default/authenticated, catalog.location, read, allow
    p, role:default/authenticated, techdocs.entity, read, allow
    
    # Allow ALL users to execute templates (Scaffolder)
    p, role:default/authenticated, scaffolder-template, read, allow
    p, role:default/authenticated, scaffolder.action.execute, use, allow
    p, role:default/authenticated, scaffolder.task, read, allow
    p, role:default/authenticated, scaffolder.task, create, allow

    # ==========================================================
    # 2. ADMIN ROLE DEFINITION (Platform Engineers)
    # ==========================================================
    # This role has full control (CRUD) over the entire system
    
    # Full control over Lightspeed (includes deleting conversations)
    p, role:default/platform-admin, lightspeed.chat, update, allow
    p, role:default/platform-admin, lightspeed.chat, delete, allow
    
    # Full control over Catalog
    p, role:default/platform-admin, catalog-entity, create, allow
    p, role:default/platform-admin, catalog-entity, update, allow
    p, role:default/platform-admin, catalog-entity, delete, allow
    p, role:default/platform-admin, catalog.location, create, allow
    p, role:default/platform-admin, catalog.location, delete, allow
    p, role:default/platform-admin, catalog.entity.create, create, allow
    
    # Full control over Templates and Tasks
    p, role:default/platform-admin, scaffolder-template, write, allow
    p, role:default/platform-admin, scaffolder.task, delete, allow
    
    # Permission and Policy Management (Very important for admins)
    p, role:default/platform-admin, permission.policy, read, allow
    p, role:default/platform-admin, permission.policy, create, allow
    p, role:default/platform-admin, permission.policy, update, allow
    p, role:default/platform-admin, permission.policy, delete, allow

    # Dynamic Plugins Management
    p, role:default/platform-admin, plugin.dynamic, read, allow
    p, role:default/platform-admin, plugin.dynamic, create, allow
    p, role:default/platform-admin, plugin.dynamic, update, allow
    p, role:default/platform-admin, plugin.dynamic, delete, allow
    p, role:default/platform-admin, plugin.dynamic, install, allow
    p, role:default/platform-admin, plugin.dynamic, uninstall, allow

    # ==========================================================
    # 3. GROUP AND USER ROLE ASSIGNMENTS
    # ==========================================================
    # Groups must match EXACTLY with the names in Keycloak
    # Keycloak groups: developers, devteam1, infrastructure, platformengineers, rhdh
    
    # Assign your user to Admin role
    g, user:default/maximilianopizarro, role:default/platform-admin
    
    # Assign Keycloak technical groups to Admin role
    # These groups exist in Keycloak and are automatically synchronized
    g, group:default/platformengineers, role:default/platform-admin
    g, group:default/infrastructure, role:default/platform-admin
    g, group:default/rhdh, role:default/platform-admin
    
    # Legacy groups (optional, only if needed for compatibility)
    # platform-team and application-team are aliases pointing to real groups
    g, group:default/platform-team, role:default/platform-admin

    # NOTE: Normal users (developers, devteam1) do not need explicit assignment
    # because they already inherit permissions from section 1 (role:default/authenticated).