kind: ConfigMap
apiVersion: v1
metadata:
  name: rhdh-rbac-policy
  labels:
    rhdh.redhat.com/ext-config-sync: 'true'
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  rbac-policy.csv: |
    # ============================================
    # FULL ADMIN PERMISSIONS FOR maximilianopizarro
    # ============================================
    
    # Note: user9-rhdh admin permissions are defined below
    
    # Catalog Entity Permissions - Full CRUD
    p, user:default/maximilianopizarro, catalog-entity, read, allow
    p, user:default/maximilianopizarro, catalog-entity, create, allow
    p, user:default/maximilianopizarro, catalog-entity, update, allow
    p, user:default/maximilianopizarro, catalog-entity, delete, allow
    
    # Catalog Location Permissions - Full CRUD
    p, user:default/maximilianopizarro, catalog.location, read, allow
    p, user:default/maximilianopizarro, catalog.location, create, allow
    p, user:default/maximilianopizarro, catalog.location, update, allow
    p, user:default/maximilianopizarro, catalog.location, delete, allow
    
    # Catalog Entity Creation Permission
    p, user:default/maximilianopizarro, catalog.entity.create, create, allow
    
    # Permission Policy Management - Full CRUD
    p, user:default/maximilianopizarro, permission.policy, read, allow
    p, user:default/maximilianopizarro, permission.policy, create, allow
    p, user:default/maximilianopizarro, permission.policy, update, allow
    p, user:default/maximilianopizarro, permission.policy, delete, allow
    
    # Scaffolder Permissions - Full Access
    p, user:default/maximilianopizarro, scaffolder-template, read, allow
    p, user:default/maximilianopizarro, scaffolder-template, write, allow
    p, user:default/maximilianopizarro, scaffolder.task, read, allow
    p, user:default/maximilianopizarro, scaffolder.task, create, allow
    p, user:default/maximilianopizarro, scaffolder.task, update, allow
    p, user:default/maximilianopizarro, scaffolder.task, delete, allow
    p, user:default/maximilianopizarro, scaffolder.action.execute, use, allow
    
    # Lightspeed (AI Chat) Permissions - Full CRUD
    p, user:default/maximilianopizarro, lightspeed.chat, read, allow
    p, user:default/maximilianopizarro, lightspeed.chat, create, allow
    p, user:default/maximilianopizarro, lightspeed.chat, update, allow
    p, user:default/maximilianopizarro, lightspeed.chat, delete, allow
    
    # TechDocs Permissions - Full Access
    p, user:default/maximilianopizarro, techdocs.entity, read, allow
    p, user:default/maximilianopizarro, techdocs.entity, create, allow
    p, user:default/maximilianopizarro, techdocs.entity, update, allow
    p, user:default/maximilianopizarro, techdocs.entity, delete, allow
    
    # API Permissions - Full Access
    p, user:default/maximilianopizarro, api.entity, read, allow
    p, user:default/maximilianopizarro, api.entity, create, allow
    p, user:default/maximilianopizarro, api.entity, update, allow
    p, user:default/maximilianopizarro, api.entity, delete, allow
    
    # Resource Permissions - Full Access
    p, user:default/maximilianopizarro, resource.entity, read, allow
    p, user:default/maximilianopizarro, resource.entity, create, allow
    p, user:default/maximilianopizarro, resource.entity, update, allow
    p, user:default/maximilianopizarro, resource.entity, delete, allow
    
    # System Permissions - Full Access
    p, user:default/maximilianopizarro, system.entity, read, allow
    p, user:default/maximilianopizarro, system.entity, create, allow
    p, user:default/maximilianopizarro, system.entity, update, allow
    p, user:default/maximilianopizarro, system.entity, delete, allow
    
    # Domain Permissions - Full Access
    p, user:default/maximilianopizarro, domain.entity, read, allow
    p, user:default/maximilianopizarro, domain.entity, create, allow
    p, user:default/maximilianopizarro, domain.entity, update, allow
    p, user:default/maximilianopizarro, domain.entity, delete, allow
    
    # Group Permissions - Full Access
    p, user:default/maximilianopizarro, group.entity, read, allow
    p, user:default/maximilianopizarro, group.entity, create, allow
    p, user:default/maximilianopizarro, group.entity, update, allow
    p, user:default/maximilianopizarro, group.entity, delete, allow
    
    # User Permissions - Full Access
    p, user:default/maximilianopizarro, user.entity, read, allow
    p, user:default/maximilianopizarro, user.entity, create, allow
    p, user:default/maximilianopizarro, user.entity, update, allow
    p, user:default/maximilianopizarro, user.entity, delete, allow
    
    # Template Permissions - Full Access
    p, user:default/maximilianopizarro, template.entity, read, allow
    p, user:default/maximilianopizarro, template.entity, create, allow
    p, user:default/maximilianopizarro, template.entity, update, allow
    p, user:default/maximilianopizarro, template.entity, delete, allow
    
    # Dynamic Plugins Permissions - Full Access (Install, View, Configure)
    p, user:default/maximilianopizarro, plugin.dynamic, read, allow
    p, user:default/maximilianopizarro, plugin.dynamic, create, allow
    p, user:default/maximilianopizarro, plugin.dynamic, update, allow
    p, user:default/maximilianopizarro, plugin.dynamic, delete, allow
    p, user:default/maximilianopizarro, plugin.dynamic, install, allow
    p, user:default/maximilianopizarro, plugin.dynamic, uninstall, allow
    
    # Plugin Configuration Permissions - Full Access
    p, user:default/maximilianopizarro, plugin.config, read, allow
    p, user:default/maximilianopizarro, plugin.config, create, allow
    p, user:default/maximilianopizarro, plugin.config, update, allow
    p, user:default/maximilianopizarro, plugin.config, delete, allow
    
    # ============================================
    # GROUP-BASED ROLE DEFINITIONS
    # Permissions are assigned to groups, not individual users
    # Users inherit permissions from their group membership in Keycloak
    # ============================================
    
    # Platform Engineers Group - Full access (platformengineers group in Keycloak)
    # Members: user7-platform, user8-platform
    p, role:default/platformengineers, lightspeed.chat, read, allow
    p, role:default/platformengineers, lightspeed.chat, create, allow
    p, role:default/platformengineers, lightspeed.chat, update, allow
    p, role:default/platformengineers, lightspeed.chat, delete, allow
    p, role:default/platformengineers, catalog-entity, read, allow
    p, role:default/platformengineers, catalog-entity, create, allow
    p, role:default/platformengineers, catalog-entity, update, allow
    p, role:default/platformengineers, catalog-entity, delete, allow
    p, role:default/platformengineers, catalog.location, read, allow
    p, role:default/platformengineers, catalog.location, create, allow
    p, role:default/platformengineers, catalog.location, update, allow
    p, role:default/platformengineers, catalog.location, delete, allow
    p, role:default/platformengineers, catalog.entity.create, create, allow
    p, role:default/platformengineers, scaffolder-template, read, allow
    p, role:default/platformengineers, scaffolder-template, write, allow
    p, role:default/platformengineers, scaffolder.task, read, allow
    p, role:default/platformengineers, scaffolder.task, create, allow
    p, role:default/platformengineers, scaffolder.task, update, allow
    p, role:default/platformengineers, scaffolder.task, delete, allow
    p, role:default/platformengineers, scaffolder.action.execute, use, allow
    p, role:default/platformengineers, permission.policy, read, allow
    p, role:default/platformengineers, plugin.dynamic, read, allow
    p, role:default/platformengineers, plugin.dynamic, install, allow
    p, role:default/platformengineers, plugin.config, read, allow
    
    # Developers Group - Standard developer access (developers group in Keycloak)
    # Members: user1-dev, user2-dev
    p, role:default/developers, lightspeed.chat, read, allow
    p, role:default/developers, lightspeed.chat, create, allow
    p, role:default/developers, catalog-entity, read, allow
    p, role:default/developers, catalog-entity, create, allow
    p, role:default/developers, catalog-entity, update, allow
    p, role:default/developers, catalog.location, read, allow
    p, role:default/developers, catalog.location, create, allow
    p, role:default/developers, catalog.entity.create, create, allow
    p, role:default/developers, scaffolder-template, read, allow
    p, role:default/developers, scaffolder.task, read, allow
    p, role:default/developers, scaffolder.action.execute, use, allow
    
    # Dev Team 1 - Standard developer access (devteam1 group in Keycloak)
    # Members: user3-devteam1, user4-devteam1
    p, role:default/devteam1, lightspeed.chat, read, allow
    p, role:default/devteam1, lightspeed.chat, create, allow
    p, role:default/devteam1, catalog-entity, read, allow
    p, role:default/devteam1, catalog-entity, create, allow
    p, role:default/devteam1, catalog-entity, update, allow
    p, role:default/devteam1, catalog.location, read, allow
    p, role:default/devteam1, catalog.location, create, allow
    p, role:default/devteam1, catalog.entity.create, create, allow
    p, role:default/devteam1, scaffolder-template, read, allow
    p, role:default/devteam1, scaffolder.task, read, allow
    p, role:default/devteam1, scaffolder.action.execute, use, allow
    
    # Infrastructure Group - Infrastructure management access (infrastructure group in Keycloak)
    # Members: user5-infra, user6-infra
    p, role:default/infrastructure, lightspeed.chat, read, allow
    p, role:default/infrastructure, lightspeed.chat, create, allow
    p, role:default/infrastructure, catalog-entity, read, allow
    p, role:default/infrastructure, catalog-entity, create, allow
    p, role:default/infrastructure, catalog-entity, update, allow
    p, role:default/infrastructure, catalog.location, read, allow
    p, role:default/infrastructure, catalog.location, create, allow
    p, role:default/infrastructure, catalog.entity.create, create, allow
    p, role:default/infrastructure, scaffolder-template, read, allow
    p, role:default/infrastructure, scaffolder.task, read, allow
    p, role:default/infrastructure, scaffolder.action.execute, use, allow
    
    # RHDH Group - Developer Hub team access (rhdh group in Keycloak)
    # Members: user9-rhdh, user10-rhdh
    p, role:default/rhdh, lightspeed.chat, read, allow
    p, role:default/rhdh, lightspeed.chat, create, allow
    p, role:default/rhdh, catalog-entity, read, allow
    p, role:default/rhdh, catalog-entity, create, allow
    p, role:default/rhdh, catalog-entity, update, allow
    p, role:default/rhdh, catalog.location, read, allow
    p, role:default/rhdh, catalog.location, create, allow
    p, role:default/rhdh, catalog.entity.create, create, allow
    p, role:default/rhdh, scaffolder-template, read, allow
    p, role:default/rhdh, scaffolder.task, read, allow
    p, role:default/rhdh, scaffolder.action.execute, use, allow
    
    # Assign groups to their roles (users inherit permissions from their group)
    # Note: Group membership is synced from Keycloak automatically
    g, group:default/platformengineers, role:default/platformengineers
    g, group:default/developers, role:default/developers
    g, group:default/devteam1, role:default/devteam1
    g, group:default/infrastructure, role:default/infrastructure
    g, group:default/rhdh, role:default/rhdh
    
    # ============================================
    # INDIVIDUAL USER ROLE ASSIGNMENTS
    # Only for users who need special permissions beyond their group
    # ============================================
    
    # maximilianopizarro - Full admin (also in admin list in app-config.yaml)
    g, user:default/maximilianopizarro, role:default/platformengineers
    
    # Note: user9-rhdh inherits permissions from 'rhdh' group automatically
    # No individual assignment needed - permissions come from group membership in Keycloak
    
    # ============================================
    # BASIC PERMISSIONS FOR ALL AUTHENTICATED USERS
    # ============================================
    # These permissions allow any authenticated user to:
    # - Sign in and access the application
    # - View catalog entities (read-only)
    # - View catalog locations (read-only)
    # - View TechDocs
    # - View APIs
    # - View Resources
    # - View Systems
    # - View Domains
    # - View Groups
    # - View Users (their own profile)
    
    # Catalog Entity Permissions - Read Only
    p, role:default/authenticated, catalog-entity, read, allow
    
    # Catalog Location Permissions - Read Only
    p, role:default/authenticated, catalog.location, read, allow
    
    # TechDocs Permissions - Read Only
    p, role:default/authenticated, techdocs.entity, read, allow
    
    # API Permissions - Read Only
    p, role:default/authenticated, api.entity, read, allow
    
    # Resource Permissions - Read Only
    p, role:default/authenticated, resource.entity, read, allow
    
    # System Permissions - Read Only
    p, role:default/authenticated, system.entity, read, allow
    
    # Domain Permissions - Read Only
    p, role:default/authenticated, domain.entity, read, allow
    
    # Group Permissions - Read Only
    p, role:default/authenticated, group.entity, read, allow
    
    # User Permissions - Read Only (users can view their own profile)
    p, role:default/authenticated, user.entity, read, allow
    
    # Scaffolder Template Permissions - Read Only (users can view templates)
    p, role:default/authenticated, scaffolder-template, read, allow
    
    # Assign all authenticated users to the authenticated role
    # This is automatically done by Backstage for logged-in users
