apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rhcl-operator
  description: Red Hat Connectivity Link Operator - Manages API gateway, OIDC authentication, and authorization policies using Kuadrant/Authorino
  annotations:
    argocd/app-name: rhcl-operator
    argocd/app-namespace: openshift-gitops
    # ArgoCD URL - Update with your cluster domain
    # Format: https://openshift-gitops-server-openshift-gitops.apps.<cluster-domain>/applications/rhcl-operator
    argocd/app-url: https://openshift-gitops-server-openshift-gitops.apps.cluster-k82pl.dynamic.redhatworkshops.io/applications/rhcl-operator
    github.com/project-slug: maximilianoPizarro/connectivity-link
  tags:
    - rhcl
    - kuadrant
    - authorino
    - api-gateway
    - oidc
    - authorization
    - connectivity-link
spec:
  type: service
  lifecycle: production
  owner: maximilianopizarro
  system: connectivity-system
  providesApis:
    - kuadrant-api
    - authorino-api
  consumesApis:
    - keycloak-api
  dependsOn:
    - component:rhbk/keycloak
    - component:servicemeshoperator3/istio-gateway

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gateway
  namespace: rhcl-operator
  description: Kubernetes Gateway API HTTPRoute resources for NeuralBank application routing
  annotations:
    argocd/app-name: rhcl-operator
    argocd/app-namespace: openshift-gitops
spec:
  type: service
  lifecycle: production
  owner: maximilianopizarro
  system: connectivity-system

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: kuadrant-api
  description: Kuadrant API Gateway management API
spec:
  type: rest
  lifecycle: production
  owner: maximilianopizarro
  definition: |
    openapi: "3.0.0"
    info:
      title: Kuadrant API Gateway Management API
      version: "1.0.0"
      description: API for managing Kuadrant API Gateway resources and policies
    paths:
      /api/gateway:
        get:
          summary: List API gateways
      /api/policy:
        get:
          summary: List gateway policies

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: authorino-api
  description: Authorino authentication and authorization API
spec:
  type: rest
  lifecycle: production
  owner: maximilianopizarro
  definition: |
    openapi: "3.0.0"
    info:
      title: Authorino Authentication and Authorization API
      version: "1.0.0"
      description: API for managing authentication and authorization policies using Authorino
    paths:
      /api/auth:
        post:
          summary: Authenticate request
      /api/authz:
        post:
          summary: Authorize request

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: connectivity-system
  description: Connectivity and API gateway system
spec:
  owner: maximilianopizarro
  domain: networking

