apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-app-httproute-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - get
  - update
  - patch
  - delete
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-app-httproute-manager-binding
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-app-httproute-manager
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops