apiVersion: extensions.kuadrant.io/v1alpha1
kind: OIDCPolicy
metadata:
  name: neuralbank-oidc
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    issuerURL: "https://rhbk.apps.cluster-lv5jx.lv5jx.sandbox2484.opentlc.com/realms/neuralbank"
    clientID: neuralbank-frontend

  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: neuralbank-front-back-route
---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: neuralbank-api-protection
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: neuralbank-front-back-route
  overrides:
    strategy: merge
    rules:
      authentication:
        oidc:
          credentials:
            cookie:
              name: jwt
          jwt:
            issuerUrl: 'https://rhbk.apps.cluster-lv5jx.lv5jx.sandbox2484.opentlc.com/realms/neuralbank'
          metrics: false
          priority: 0
      response:
        success: {}
        unauthenticated:
          code: 302
          headers:
            location:
            value: "https://rhbk.apps.cluster-lv5jx.lv5jx.sandbox2484.opentlc.com/realms/neuralbank/protocol/openid-connect/auth?client_id=neuralbank-frontend&redirect_uri=https%3A%2F%2Fneuralbank.apps.cluster-lv5jx.lv5jx.sandbox2484.opentlc.com/auth/callback&response_type=code&scope=openid"
            set-cookie:
              expression: |-
                "target=" + request.path + "; HttpOnly; SameSite=Lax; Path=/; Max-Age=3600"
          when:
            any:
              - selector: request.path
                operator: matches
                value: ^/api
              - selector: request.path
                operator: matches
                value: ^/swagger-ui
              - selector: request.path
                operator: matches
                value: ^/q

        exclude:
          - selector: request.path
            operator: matches
            value: ^/auth/callback