apiVersion: extensions.kuadrant.io/v1alpha1
kind: OIDCPolicy
metadata:
  name: neuralbank-oidc
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    issuerURL: "https://rhbk.apps.cluster-lv5jx.lv5jx.sandbox2484.opentlc.com/realms/neuralbank"
    clientID: neuralbank-frontend

  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: neuralbank-front-back-route
---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: neuralbank-api-protection
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: neuralbank-front-back-route

  overrides:
    strategy: merge
    rules:
      authorization:
        protect-api:
          metrics: false
          priority: 0
          opa:
            rego: |
              package authentication

              hostname := input.request.host
              
              callback_url := concat("", ["https://", hostname, "/auth/callback"])
              
              authz_url := concat("", [
                  "https://rhbk.apps.cluster-lv5jx.lv5jx.sandbox2484.opentlc.com/realms/neuralbank/oauth/authorize?",
                  "client_id=neuralbank-frontend",
                  "&redirect_uri=", url.query_encode(callback_url),
                  "&response_type=code&scope=openid"
              ])

              allow = false {
                  cookie := input.request.headers.cookie
                  cookie == ""
              }
              allow = false {
                  cookie := input.request.headers.cookie
                  not contains(cookie, "jwt=")
              }

              allow = true {
                  cookie := input.request.headers.cookie
                  contains(cookie, "jwt=")
              }
              
              response.status_code := 302 { not allow }
              response.headers := {"Location": authz_url} { not allow }
          when:
            - selector: request.path
              operator: matches
              value: ^/api
            - selector: request.path
              operator: matches
              value: ^/swagger-ui
            - selector: request.path
              operator: matches
              value: ^/q

