# Gateway in istio-system so Istio controller picks it up. HTTPRoute in litemaas (backendRefs to litemaas services).
# All traffic through single host litemaas.apps.<domain>: / -> frontend, /api -> backend, /v1 and /q -> LiteLLM.
# Namespaces set via kustomization patches (Gateway -> istio-system, HTTPRoute -> litemaas).
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: litemaas-gateway
  namespace: neuralbank-stack
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  gatewayClassName: istio
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      name: http
      port: 8080
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: All
      name: https
      port: 443
      protocol: HTTPS
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: litemaas-route
  namespace: litemaas
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  hostnames:
    - litemaas.apps.cluster-gpzvq.gpzvq.sandbox670.opentlc.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: litemaas-gateway
      namespace: istio-system
  rules:
    # /api -> LiteMaaS backend
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: backend
          port: 8080
    # /v1 and /q -> LiteLLM API
    - matches:
        - path:
            type: PathPrefix
            value: /v1
        - path:
            type: PathPrefix
            value: /q
      backendRefs:
        - name: litellm
          port: 4000
    # / -> frontend
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frontend
          port: 8080
