apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: neuralbank-front-back-route
  annotations:
    argocd.argoproj.io/sync-wave: "5"   
spec:
  parentRefs:
    - name: neuralbank-gateway
      namespace: istio-system
  
  hostnames:
    - "neuralbank.apps.cluster-lv5jx.lv5jx.sandbox2484.opentlc.com"

  rules:
    # ------------------------------------------------------------
    # REGLA SEGURA: API y Swagger (Protegida por AuthPolicy)
    # ------------------------------------------------------------
    - name: api-secured # <-- NUEVO NOMBRE: Target para la AuthPolicy
      matches:
        - path:
            type: PathPrefix
            value: /api
        - path:
            type: PathPrefix
            value: /swagger-ui
        - path:
            type: PathPrefix
            value: /q
      backendRefs:
        - name: neuralbank-backend-svc
          port: 8080

    # ------------------------------------------------------------
    # REGLA DESPROTEGIDA: Ruta Raíz (No tiene AuthPolicy asociada)
    # ------------------------------------------------------------
    - name: root-unsecured # <-- NUEVO NOMBRE: Permite el acceso sin autenticación
      matches:
        - path:
            type: PathPrefix
            value: /        
      backendRefs:
        - name: neuralbank-frontend-svc
          port: 8080
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neuralbank-app-writer
  namespace: neuralbank-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
  - apiGroups:
      - "" 
    resources:
      - services
      - secrets
      - configmaps
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kuadrant.io
    resources:
      - authpolicies
      - kuadrants
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - extensions.kuadrant.io
    resources:
      - oidcpolicies 
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neuralbank-app-binding
  namespace: neuralbank-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: Role
  name: neuralbank-app-writer
  apiGroup: rbac.authorization.k8s.io
