apiVersion: extensions.kuadrant.io/v1alpha1
kind: OIDCPolicy
metadata:
  name: neuralbank-oidc
  annotations:
    argocd.argoproj.io/sync-wave: "5"
# KEYCLOAK_HOST_PLACEHOLDER / APP_HOST_PLACEHOLDER replaced by install.sh or Ansible; clientSecret by playbook (client "neuralbank")
spec:
  provider:
    issuerURL: "https://KEYCLOAK_HOST_PLACEHOLDER/realms/neuralbank"
    clientID: neuralbank-frontend
    clientSecret: "OIDC_CLIENT_SECRET_PLACEHOLDER"
    authorizationEndpoint: "https://KEYCLOAK_HOST_PLACEHOLDER/realms/neuralbank/protocol/openid-connect/auth"
    redirectURI: "https://APP_HOST_PLACEHOLDER/auth/callback"
    tokenEndpoint: "https://KEYCLOAK_HOST_PLACEHOLDER/realms/neuralbank/protocol/openid-connect/token"
   
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: neuralbank-api-route
    namespace: neuralbank-stack

  auth:
    tokenSource:
      authorizationHeader:
        prefix: Bearer
        name: Authorization

      cookie:
        name: jwt
