apiVersion: extensions.kuadrant.io/v1alpha1
kind: OIDCPolicy
metadata:
  name: neuralbank-oidc
  annotations:
    argocd.argoproj.io/sync-wave: "5"
# rhbk.apps.cluster-zrg7z.zrg7z.sandbox489.opentlc.com / neuralbank.apps.cluster-zrg7z.zrg7z.sandbox489.opentlc.com replaced by install.sh or Ansible; clientSecret by playbook (client "neuralbank")
spec:
  provider:
    issuerURL: "https://rhbk.apps.cluster-zrg7z.zrg7z.sandbox489.opentlc.com/realms/neuralbank"
    clientID: neuralbank-frontend
    clientSecret: "OIDC_CLIENT_SECRET_PLACEHOLDER"
    authorizationEndpoint: "https://rhbk.apps.cluster-zrg7z.zrg7z.sandbox489.opentlc.com/realms/neuralbank/protocol/openid-connect/auth"
    redirectURI: "https://neuralbank.apps.cluster-zrg7z.zrg7z.sandbox489.opentlc.com/auth/callback"
    tokenEndpoint: "https://rhbk.apps.cluster-zrg7z.zrg7z.sandbox489.opentlc.com/realms/neuralbank/protocol/openid-connect/token"
   
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: neuralbank-api-route
    namespace: neuralbank-stack

  auth:
    tokenSource:
      authorizationHeader:
        prefix: Bearer
        name: Authorization

      cookie:
        name: jwt
