apiVersion: v1
kind: Secret
metadata:
  name: neuralbank-oidc-client-secret
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
data:
  clientSecret: bmt4bWx4TjF3SUNTWXJaMVFvSWVVdFZ2ampDS2ZlWGg=
---
apiVersion: extensions.kuadrant.io/v1alpha1
kind: OIDCPolicy
metadata:
  name: neuralbank-oidc
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    issuerURL: "https://rhbk.apps.cluster-lv5jx.lv5jx.sandbox2484.opentlc.com/realms/neuralbank"
    clientID: neuralbank
    clientSecretRef:
      name: neuralbank-oidc-client-secret
      key: clientSecret
    authorizationEndpoint : "https://rhbk.apps.cluster-lv5jx.lv5jx.sandbox2484.opentlc.com/realms/neuralbank/protocol/openid-connect/auth"
    redirectURI : "https://neuralbank.apps.cluster-lv5jx.lv5jx.sandbox2484.opentlc.com/auth/callback"
    tokenEndpoint: "https://rhbk.apps.cluster-lv5jx.lv5jx.sandbox2484.opentlc.com/realms/neuralbank/protocol/openid-connect/token"
   
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: neuralbank-front-back-route

  auth:
    tokenSource:
      authorizationHeader:
        prefix: Bearer
        name: Authorization

      cookie:
        name: jwt