apiVersion: extensions.kuadrant.io/v1alpha1
kind: OIDCPolicy
metadata:
  name: neuralbank-oidc
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    issuerURL: "http://rhbk.apps.cluster-kbtgl.kbtgl.sandbox4020.opentlc.com:8080/realms/neuralbank"
    clientID: neuralbank-frontend
    clientSecret: "FYtNXAyn6eRmWxHIig7oLhK3zxQ1nLaF"
    
    authorizationEndpoint: "https://rhbk.apps.cluster-kbtgl.kbtgl.sandbox4020.opentlc.com/realms/neuralbank/protocol/openid-connect/auth"
    tokenEndpoint: "https://rhbk.apps.cluster-kbtgl.kbtgl.sandbox4020.opentlc.com/realms/neuralbank/protocol/openid-connect/token"
    redirectURI: "https://neuralbank.apps.cluster-kbtgl.kbtgl.sandbox4020.opentlc.com/auth/callback"
   
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: neuralbank-api-route

  auth:
    tokenSource:
      authorizationHeader:
        prefix: Bearer
        name: Authorization
      cookie:
        name: jwt