# RateLimitPolicy to limit requests to /api/customers endpoint
# This policy limits "Javier Rodríguez Torres" to 10 requests per minute on /api/customers
# 
# To apply the limit to ALL users (each user gets 10 requests per minute):
#   Remove the second condition (auth.identity.username equals "Javier Rodríguez Torres")
#
# To change the limit window (e.g., per second instead of per minute):
#   Change window: 1m to window: 1s
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: neuralbank-customers-ratelimit
  namespace: neuralbank-stack
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: neuralbank-api-route
    namespace: neuralbank-stack
  limits:
    customers-api-per-user:
      conditions:
        - operator: matches
          selector: request.path
          value: /api/customers
        - operator: equals
          selector: auth.identity.username
          value: Javier Rodríguez Torres
      counters:
        - expression: auth.identity.username
      rates:
        - limit: 10
          window: 1m

