# TokenRateLimitPolicy for LiteMaaS gateway (istio-system).
# Applies rate limits by tier: free (2/min), gold (200k/24h when in group "gold").
apiVersion: kuadrant.io/v1alpha1
kind: TokenRateLimitPolicy
metadata:
  name: token-limit-litemaas
  namespace: istio-system
spec:
  limits:
    free:
      rates:
        - limit: 2
          window: 1m
    gold:
      counters:
        - expression: auth.identity.userid
      rates:
        - limit: 200000
          window: 24h
      when:
        - predicate: 'request.auth.claims["kuadrant.io/groups"].split(",").exists(g, g == "gold")'
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: litemaas-gateway
