apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: librechat
  description: A Helm chart for deploying LibreChat, an open-source, AI-powered chat application. Enhanced ChatGPT Clone: Features Agents, MCP, DeepSeek, Anthropic, AWS, OpenAI, Responses API, Azure, Groq, o1, GPT-5, Mistral, OpenRouter, Vertex AI, Gemini, Artifacts, AI model switching, message search, Code Interpreter, langchain, DALL-E-3, OpenAPI Actions, Functions, Secure Multi-User Auth, Presets, open-source for self-hosting. Active.
  annotations:
    gitlab.com/project-slug: maximilianoPizarro/connectivity-link
  tags:
    - tekton
    - pipelines
    - cicd
    - helm
    - external-chart
spec:
  type: service
  lifecycle: production
  owner: maximilianopizarro
  system: cicd-platform
  dependsOn:
    - component:operators/pipelines-operator

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: cicd-platform
  description: CI/CD and pipeline automation platform
spec:
  owner: maximilianopizarro
  domain: devops

